### ISSUE TITLE
Formally deprecate hypothesis.extra.fakefactory

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#1002]
As far as I know, `hypothesis.extra.fakefactory` exists mostly because Hypothesis didn't have an `emails()` strategy when the Django extra needed to infer a strategy for `EmailField`s.  Now we do - and `fakefactory()` is neither used internally nor recommended for users.

My view is that we should either deprecate this extra (my preference), or decide to support it properly (including newer versions and better shrinking).

Is there more background that I'm missing?  Would anyone object to removing it after a deprecation period?

**Comment by DRMacIver** [comment]
I'm keen on formally deprecating it, yeah.
