### ISSUE TITLE
eliminating the `buffer_size` setting

### ISSUE THREAD

**Issue by bukzor** [HypothesisWorks/hypothesis-python#1013]
As per #535, this setting should be eliminated. 

> buffer_size - very bad. Totally about Hypothesis internals, totally undocumented as to what it really means. Hypothesis should figure out something sensible to do here and then do it.

Let's discuss how in this ticket. I have several full-time days to devote to this if we can figure it out.

**Comment by bukzor** [comment]
My ideas:

Let's eliminate the buffer-overrun failure mode. The rationale for hypothesis to care about overrun (if I understand it, please correct me if not) is that a large buffer will slow tests down inordinately. We already have plenty of guards against slowness though. Let's auto-expand the buffer, but ensure that a large buffer doesn't violate the time limits.

Do you agree? Do you have a better solution in mind?

**Comment by Zac-HD** [comment]
@DRMacIver had some concerns that I don't think you've addressed:

> I think it's really very unlikely that you're going to be able to make [expanding the buffer] work in a way that doesn't break a lot of existing well supported use cases. This isn't an easy problem, and the fixed buffer size is currently carrying a lot of weight in terms of how various cases are handled (deeply nested and recursive structures in particular). ... I would be very surprised if this proved to be a promising direction because fundamentally the outcome you are trying to achieve is something that looks like an error for normal operation.

Personally, I'd be delighted but very, very surprised if expanding the buffer works without catastrophic effects on eg recursive strategies, which rely on a fixed buffer size to avoid unbounded growth.

For your particular example of a strategy requiring 2**18 bytes of buffer, it will almost certainly be easier (and give better results) to improve the strategy - we did something similar for Numpy arrays drawing sparse entries.  If you can post reproducible examples we can help here, if not we'll be limited to fairly general advice which is mostly in the docs already.

**Comment by bukzor** [comment]
Thanks. How do we address them? It's too vague to argue, currently. If you can give an example, we can have a concrete discussion. Are there not recursive strategies in the test suite? I've got it passing.

Simplifying any particular strategy isn't for this ticket.

**Comment by Zac-HD** [comment]
Try running the benchmark suite, and if that looks OK open a pull request so we can see your proposal! I agree that this is too vague otherwise :smile:

**Comment by bukzor** [comment]
Can do!

**Comment by Zac-HD** [comment]
Closing this as redundant with #535 - just make the pull 😉

**Comment by bukzor** [comment]
I was hoping to engender a bit more discussion before I create something (that I consider) pull-worthy.
Oh well. It will be a few weeks before this is ready, I think, considering my other distractions.
