### ISSUE TITLE
Have Travis auto-commit any changes required for 'check-format'

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis-python#1015]
While I’m stealing ideas from work, we might want to borrow https://github.com/wellcometrust/platform/pull/1255

Because Travis know enough to auto-format code to pass "make check-format", and is already able to push to our repo, we should enhance it so that if it detects formatting issues on a PR, it auto-commits the necessary changes and pushes them to GitHub.

This saves the PR author a bit of work.

It also speeds up our builds – as soon as Travis pushes the new commit, it will auto-cancel the old build with the bad formatting. It reduces the amount of time it spends building patches that have a known and easily fixable problem.

**Comment by Zac-HD** [comment]
I like the concept, but two notes:

- AFAIK, Travis only cancels builds that haven't started yet, so this will only reduce contention if the author has pushed two commits.  Still worth doing IMO.
- Personally I'd find this pretty annoying, because I often end up collecting a few changes after a CI run.  Other humans may also tend to assume that other people don't push to their branches without good reason and waiting a while.  However it would be *fantastic* for pyup branches.

**Comment by alexwlchan** [comment]
> AFAIK, Travis only cancels builds that haven't started yet

I don’t think so – I think it cancels pending jobs (or even in-progress jobs) if a new commit arrives on a pull request. Unless I cancelled this manually, I think this build was cancelled by just such an auto format commit: https://travis-ci.org/wellcometrust/platform/builds/313048283

> Personally I'd find this pretty annoying, because I often end up collecting a few changes after a CI run. Other humans may also tend to assume that other people don't push to their branches without good reason and waiting a while.

Fair, the platform repo only has three core committers and we all sit within earshot of each other, it was easy to agree this was a Good Thing to do. May be harder for Hypothesis.

> However it would be fantastic for pyup branches.

Ooooh.

**Comment by Zac-HD** [comment]
[Travis docs](https://docs.travis-ci.com/user/customizing-the-build/#Building-only-the-latest-commit):

> If you are only interested in building the most recent commit on each branch you can use this new feature to automatically cancel older builds in the queue that are not yet running.

**Comment by DRMacIver** [comment]
> May be harder for Hypothesis.

One thing to consider here is that most work on Hypothesis is actually done with external forks of the repo (I'm not sure which of the team currently work on the repo and which work on a fork, but it's definitely a mix, and everyone not on the team works on a fork by definition), so most pull requests Travis *can't* push to.

**Comment by Zac-HD** [comment]
GitHub actually grants Hypothesis maintainers push access to branches of forks that are in a pull request, so technically we *could*.  But as above, this is a substantial violation of norms and IMO we *shouldn't*.

**Comment by DRMacIver** [comment]
Oh, huh. I did not know that.

**Comment by alexwlchan** [comment]
It’s opt-out whether you allow maintainers to do that; agree we definitely shouldn’t do it on forks!

It feels like this probably isn’t going to work, or at least not without a rethinking about exactly when and who it runs for, so I’m going to drop this idea for now.
