### ISSUE TITLE
Should Travis skip building the "Bump version to X.Y.Z and update changelog" commits?

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis-python#1016]
It already knows the code passes, or it would never have created the commit in the first place.

**Comment by Zac-HD** [comment]
IMO yes, and we should just put `[ci skip]` in the commit message.

**Comment by Zac-HD** [comment]
I think this job is the run which actually uploads the new version to PyPI and pushes tags, so we probably shouldn't?

It would be easy to implement though, just add `\n\n[ci skip]` to the commit message in hypothesistooling.

**Comment by alexwlchan** [comment]
> I think this job is the run which actually uploads the new version to PyPI and pushes tags, so we probably shouldn't?

I don't think so. This is the code that runs in `deploy.py`, which runs on the commit which merged the PR to GitHub:

```python
print('Release seems good. Pushing to github now.')

tools.create_tag_and_push()

print('Now uploading to pypi.')

subprocess.check_call([
    sys.executable, '-m', 'twine', 'upload',
    '--config-file', './.pypirc',
    os.path.join(DIST, '*'),
])
```

We push this commit to GitHub and deploy in the same build. The "Bump version to X.Y.Z" commit doesn't do anything release-related.

Compare the two most recent builds on master:

https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/314143368
https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/314153513

**Comment by Zac-HD** [comment]
Yep, after actually reading the relevant code I agree 😄
