### ISSUE TITLE
Proposal: Drop the benchmarks job

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#1038]
I still like the concept, but I haven't actually found it to be useful in practice - we don't really have a defined decision making process off the back of it, and it contributes a significant amount of lag to development.

Any competing opinions? Does anyone actually find it useful?

**Comment by alexwlchan** [comment]
> Does anyone actually find it useful?

Not me.

**Comment by Zac-HD** [comment]
If it's not useful for decision-making, drop it.

Another controversial (?) opinion: we should make pytest less verbose on Travis.  I've never found printing every test name useful, and it slows down loading and scrolling of logs enormously.
