### ISSUE TITLE
Possible parameter generation optimisation for Django

### ISSUE THREAD

**Issue by mr-bo-jangles** [HypothesisWorks/hypothesis-python#1065]
It would be useful for testing methods that take Django model instances, if you could specify a property to be generated once and then reused as it's required in the DB, but not important to the test.

**Comment by Zac-HD** [comment]
If the performance hit isn't too big, I'd just leave this to the shrinker and avoid limiting the power of the tests.

If you *are* running into performance issues (and can demonstrate this with profiling!), you can already specify an exact strategy for each field of the model.  Using `just()` will then avoid drawing and shrinking any examples from Hypothesis, eg:

    models(Customer, name=just(''), age=just(0))

Does this solve your problem?

**Comment by mr-bo-jangles** [comment]
I don't appear to be getting notifications on replies so sorry about the delay on getting back to this. 

My general reasoning behind this is that I have some really wide models, some with up to 30 fields, all of which are required fields and so they need to be filled with something. However their values mean literally nothing in the operation of the test, but because they're so numerous I'd prefer not having to specify each one fully every time and instead list the ones that I am interested in with the rest being generated as a one off and then reused between iterations. I was seeing it as a halfway house between hard coded values and the current system.

**Comment by Zac-HD** [comment]
As a design issue we don't support this - you either use a strategy or you don't; one-off generation is just asking for unminimised and non-reproducible bugs.  Again, in this case I'd just let the strategy work and trust Hypothesis to provide (minimal) examples appropriately.

For ergonomics: you can write a helper function, or do something like `models(**minimal_kwargs.update(kwargs_for_this_test))`.

**Comment by mr-bo-jangles** [comment]
Fair enough, I could argue that it's the same search hypothesis already does, just at a much slower rate of once per test case instead of once per test case iteration, however I can see how that might cause issues if it was incorrectly handled.

Is there any chance you could add that last bit to the Django documentation as a protip? It's actually pretty helpful
