### ISSUE TITLE
Tests fail on python 3.5 in conda-forge

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis-python#1074]
It seems that some tests fail for 3.44.16 on python 3.5. See log at: https://circleci.com/gh/jochym/hypothesis-feedstock/222?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
and https://ci.appveyor.com/project/conda-forge/hypothesis-feedstock/build/1.0.123

**Comment by DRMacIver** [comment]
Ugh. I suspect this is one of those fun "typing module changes its behaviour in patch releases" things. @Zac-HD, this is in your recent work, would you mind taking a look?

**Comment by Zac-HD** [comment]
Ugh.  I can't reproduce this locally even on Python 3.5.4, but the cause is clear and patch straight-forward.

**Comment by jochym** [comment]
Is this going to be in the next release? If so I will just wait with the conda-forge build.

**Comment by DRMacIver** [comment]
@jochym Probably the next, certainly one that's soon, yeah.
