### ISSUE TITLE
Use dictionaries strategy when keys and values are not known until test time

### ISSUE THREAD

**Issue by rbdixon** [HypothesisWorks/hypothesis-python#1089]
I'm using pytest with the current pip version of hypothesis. My goal is to call a test function while using a strategy such as `dictionaries` or `fixeddictionaries`. The catch is that the parameters I will need to specify the strategy will not be known until test execution time.

This lead me to thinking that I'd want to build a parameterized decorator that, at runtime, runs `given()` to create the test function decorator and then calls the decorator with the test function and test parameters. It all seems smart... till pytest complains about not being able to find the fixture name corresponding to the parameter I'm expecting hypothesis to provide.

I glanced at the source and saw that there are some clever machinations going on to do surgery on the function parameters. Perhaps I'm inhibiting that or doing this the wrong way?

Any advice? Test case attached.

```
$ pytest test_fixture.py 

================================================================ ERRORS ================================================================
____________________________________________________ ERROR at setup of test_dynamic ____________________________________________________
file /Users/rbdixon/src/hypothesis/test/test_fixture.py, line 54
  @env_mutilator('test_env')
  def test_dynamic(api, auth_env, test_env):
E       fixture 'test_env' not found
>       available fixtures: api, auth_env, cache, capfd, capsys, doctest_namespace, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

Test code:

```
import pytest
from collections import namedtuple
from hypothesis import given
from hypothesis.strategies import integers, fixed_dictionaries
from decorator import decorator
from inspect import signature

@pytest.fixture
def auth_env():
    'Specifies the keys for the generated dictionary'

    return set(['a', 'b', 'c'])

@pytest.fixture
def api():
    'Placeholder for something more complex'

    return namedtuple('API', ('env'))({'a': 1, 'b': 2, 'c': 3})

def get_funcargs(func, func_args, func_kwargs):
    'Get the test function arguments by name.'

    sig = signature(func)
    ba = sig.bind(*func_args, **func_kwargs)

    return ba.arguments

def env_mutilator(env_param_name=None):

    @decorator
    def wrapper(func, *func_args, **func_kwargs):
        params = get_funcargs(func, func_args, func_kwargs)
        env = params['api'].env
        auth_env = params['auth_env'].env

        # build the mapper for the fixed_dictionaries strategy
        test_dict = { key: integers() for key in auth_env }

        hypoargs = dict()
        hypoargs[env_param_name]=fixed_dictionaries(test_dict)

        # Get the hypothesis decorator
        hypodec = given(**hypoargs)

        return hypodec(func)(*func_args, **func_kwargs)

    return wrapper

@given(test_env=fixed_dictionaries({'a': integers(), 'b': integers(), 'c': integers()}))
def test_static(test_env):
    'Simple static example.'
    assert test_env['a'] != 100

@env_mutilator('test_env')
def test_dynamic(api, auth_env, test_env):
    'Should be called test_env drawn from the strategy that is built at run time.'

    print(test_env)
    assert test_env['a'] != 100

```

**Comment by Zac-HD** [comment]
> I'm using pytest with the current pip version of hypothesis. My goal is to call a test function while using a strategy such as dictionaries or fixeddictionaries. The catch is that the parameters I will need to specify the strategy will not be known until test execution time.

Instead of wrapping things in even more layers, I'd [use `st.data()` to draw from strategies defined inside your test function](https://hypothesis.readthedocs.io/en/latest/data.html#interactive-draw).  `data()` is designed for exactly this kind of case, and while it might be a little more verbose (for the test) the code should also be clear to any future readers 😄 

Illustratively, thus:

```python
@given(data=st.data())
def test_dynamic(api, auth_env, data):
    test_env = data.draw(fixed_dictionaries({k: st.integers() for k in auth_env})
                         label='auth_env=' + repr(auth_env))
    print(test_env)
    assert test_env['a'] != 100

**Comment by rbdixon** [comment]
Thank you.... this is much easier than the crazy path I was going down. I'd read the `st.data()` section previously but I didn't connect my problem to that solution today.
