### ISSUE TITLE
Argument-renaming decorator should indent added docstring, error on old+new args

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#1111]
Occasionally, we have changed the names of various arguments - for example to [`hypothesis.strategies.datetimes`](https://github.com/HypothesisWorks/hypothesis-python/blob/5f3e942504f4b3651481fd8bfa697d938a792f1b/src/hypothesis/strategies.py#L1375-L1384)

This is done via [`hypothesis.internal.renaming`](https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/internal/renaming.py), which has two problems:

1. ~~If both old and new arguments are given, the old overrides the new.  This should be an error - currently it  behaves exactly as if only the old argument was passed.  In my opinion this should be fixed in a minor release; while technically a breaking change the broken behavior has *always* been deprecated and never worked.  (cc @DRMacIver)
   Raising `InvalidArgument` if `t in kwargs` before noting the deprecation would be sufficient, along with a test that giving a deprecated argument and the new argument that replaced it is an error.~~
   This is simply not worth the effort to change again - the deprecation-free paths are working as intended, so we'll just clean it up in the eventual Hypothesis 4.0.

2. A section mentioning the changes is appended to the docstring, but without any indentation.  This then changes the output of [`inspect.cleandoc`](https://docs.python.org/3/library/inspect.html#inspect.cleandoc), preserving indentation after the first line that would otherwise be removed.  [Here's an example](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.datetimes) of the results via Sphinx (at tag 3.45.0, once we solve #1110).
   Instead, we should either work out the minimal indentation for lines after the first and match that, or just call `cleandoc` on the docstring before appending to it 😉

**Comment by dchudz** [comment]
I think we also have:

3. If a renamed function takes a `not_none` default for the new argument, but is passed `None` with the old argument name, the default value `not_none` will be used instead of the explicitly passed `None`.

For example, this test would currently fail:

```
@renamed_arguments(old_arg='new_arg')
def g(new_arg='hi', old_arg=None):
    return new_arg

def test_pass_none_as_old_arg_goes_through():
    assert g(old_arg=None) is None
```

I guess it's not super common for functions with non-`None` defaults to take `None` as a meaningful value (and I don't think anywhere `@renamed_arguments` is currently used is like that)... but users should at least get an error in that case, instead of silently getting the `new_arg` default.

This happens because `v is not None` is used as part of the check for whether we should issue the deprecation. 

I haven't thought yet about whether it's easy/possible to achieve the original goal without thus behavior that I claim is a bug.

**Comment by dchudz** [comment]
There might be some wacky signature-changing stuff that's possible, where the user sees a sensible-looking signature but the actual defaults give us nice sentinels. Dunno if we really want to go down that road.

**Comment by dchudz** [comment]
I think my comments about (3) also apply to fixing (1).

I could be confused, but just to be clear about why I think this is more complicated than you say:

> Raising `InvalidArgument` if `t in kwargs` ...  would be sufficient

I don't think this is right, since `kwargs` will contain both passed arguments *and* default arguments.

For example, if I put `print(kwargs)` before the loop, I get:

```
In [1]: from hypothesis.internal.renaming import renamed_arguments

In [2]: @renamed_arguments(old_arg='new_arg')
   ...: def f(new_arg=None, old_arg=None):
   ...:     return new_arg
   ...:

In [3]: f()
{'new_arg': None, 'old_arg': None}
```

**Comment by Zac-HD** [comment]
> 3\. If a renamed function takes a not_none default for the new argument, but is passed None with the old argument name, the default value not_none will be used instead of the explicitly passed None.

This is working as intended, so long as None was the old default.  It's worth adding a comment to this effect, but because this is purely internal API I don't think we need any validation logic - it's only used occasionally and under heavy scrutiny!

`hypothesis.not_set` would be the singleton to use (it gives nice-looking signatures), but I would simply stick with `None` - the old default behavior *should* become the new default behavior.  Since we aim not to need `@rename_arguments` anywhere else, let's not upgrade it for requirements we don't have.

> `kwargs` will contain both passed arguments and default arguments

Right, raise if `kwargs.get(t) is not None`, then.

**Comment by dchudz** [comment]
> This is working as intended, so long as None was the old default.

You mean so long as None was the default from before the rename? But that's not ever the case -- the default from before the rename is always the new default for the new arg name. (I looked.)

> Right, raise if kwargs.get(t) is not None, then.

I think you mean `is not <whatever t's default value is>` (which isn't `None`). 

That could *mostly* solve (1) (if we add code for looking up the default with something like `inspect.getargspec`) by raising `InvalidArgument` if e.g. `max_value` and `max_delta` are *both* different from their defaults (which is the only way I can see to know that the user specified both).

But I'm claiming there's no way to look at `kwargs` and distinguish a user who said

`timedeltas(min_delta=timedelta(0), max_value=dt.timedelta.max, max_delta=dt.timedelta.max)` 

from one who said

`timedeltas(min_delta=timedelta(0), max_delta=dt.timedelta.max)`.

Sorry if I'm misunderstanding you and/or just confused.

**Comment by dchudz** [comment]
Sorry if this is nitpicking, but just to be unambiguous:

In point (3), I was saying that the rename changed the *user-facing* API in ways that weren't intended. 

Before the rename, it looks like `timedeltas(min_delta=dt.timedelta(0), max_delta=None).example()` would have been an exception. Now it gives you a default for `max_delta`.

Not a big deal, maybe I shouldn't have mentioned it. (And if the renamer gets no more use, or only very careful use... then yeah, it won't be a big deal in the future either.)

**Comment by Zac-HD** [comment]
Ooh, I see now - sorry!  My inclination is just to *avoid* layering backwards-compatible deprecations, so how about leaving that well alone and just fixing the indentation 😥

**Comment by dchudz** [comment]
😛 makes sense!

**Comment by alexwlchan** [comment]
Re-opening – the comment on #1119 says it just fixes item 1.

**Comment by Zac-HD** [comment]
I think closing it is correct - we decided that it's better to leave an ambiguous edge case than to write a deprecation layer in the deprecation layer.  The "bug": passing both old and new arguments issues a deprecation warning, then uses the old argument; this should probably be an error, but not worth fixing now.  @dchudz left a nice note on the decorator too, so we'll look at it again if it ever gets applied to something else.
