### ISSUE TITLE
Warn on use of django.test.TestCase with Hypothesis

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#1113]
As per #1112, currently if you use the base Django test class instead of our one it will fail in really confusing and non-obvious ways. 

We should detect this situation and warn about it. Possibly even error - I think this would be backwards compatible as there's basically no way this can be not broken at the moment.

**Comment by Zac-HD** [comment]
Related to #1071 and the (hopefully someday soon) solution in #1072 - in both cases we need to check the type of the class that our test method is defined on.
