### ISSUE TITLE
setup_example and teardown_example are undocumented

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#1126]
Obviously this is bad.  In particular, the relationship between the return value of `setup_example` and arguments to `teardown_example` are mysterious.

**Comment by Zac-HD** [comment]
Duplicate of #59 - this is an *old* issue!

**Comment by DRMacIver** [comment]
> Obviously this is bad. In particular, the relationship between the return value of setup_example and arguments to teardown_example are mysterious.

This is actually deliberate. They *used* to be documented, but it's basically a terrible API, so it went unofficial and internal, but it's not going anywhere until we come up with a better lifecycle API.

**Comment by Zac-HD** [comment]
Do you mean the per-example setup/teardown in general, or just the token part?  If the former, what makes you call it a terrible API?  If the latter, why not disable & deprecate that while documenting the rest?

Given that per-example setup and teardown is essential for a range of purposes (especially with databases - see eg the Django extra), I'd like to document this even if it's marked as deprecated or otherwise with caveats.

**Comment by DRMacIver** [comment]
> Do you mean the per-example setup/teardown in general, or just the token part? If the former, what makes you call it a terrible API? 

Two main reasons:

* I think single `setUp/tearDown` APIs are *intrinsically terrible*. They do not compose well at all, and they separate out logic that should be together.
* Given that we are pytest-by-default it's particularly bad to only support set up and teardown for class based tests.

Where there is an existing terrible set up and tear down mechanism that we can reasonably support, we should ideally do so, but I really don't want us inflicting more upon the world.

> I'd like to document this even if it's marked as deprecated or otherwise with caveats.

My caveats are "I will be sad if new people start using it and I would like to axe this really aggressively as soon as we have a better API", so I'm basically entirely against this plan sorry.

From my point of view, using this API is strictly worse than just writing a function or a context manager or something, and I would rather not give people the option to do that.

**Comment by psukys** [comment]
@DRMacIver what about using handlers for different test runners so that appropriate setup&teardown methods are being used?

**Comment by Zac-HD** [comment]
@psukys - we added a hook that test runners can use in #1343, and it's already being used (for example) in `pytest-trio` to wrap async functions with the required event loop.
