### ISSUE TITLE
deprecate calling `@settings` without `@given`

### ISSUE THREAD

**Issue by dchudz** [HypothesisWorks/hypothesis-python#1135]
Settings should give a deprecation warning if you tried to call the test function without having applied given to it.

**Comment by Zac-HD** [comment]
Note that `@given` and `@settings` can be applied in any order - it's not impossible, but detecting misuse won't be easy.

**Comment by DRMacIver** [comment]
I think the way to do it would be that when settings is applied before given it returns a dummy function that wraps the test and emits the warning. When given is applied to that function it unwraps it.

It'll be annoying, but should be pretty doable.

**Comment by Zac-HD** [comment]
That, and make `@settings` skip the wrapping if `getattr(func, 'is_hypothesis_test')` should do the trick :smile:
