### ISSUE TITLE
Biasing of strings

### ISSUE THREAD

**Issue by bukzor** [HypothesisWorks/hypothesis-python#1168]
In my application, I do want to cover the space of all strings, but the assertions are much more meaningful if the strings match. It's similar to inserting and selecting strings from a database.

I'd like to keep randomizing the strings, and provide coverage for non-matching queries, but add a bias to the strategy such that choosing two matching strings is somewhat likely.

Have you encountered this (or similar) problem? Is there a known solution? I've devised my own solution, but it's not elegant nor efficient.

Please let me know if there's a more appropriate forum for this question! I couldn't think of anything better than a GitHub issue.

**Comment by Zac-HD** [comment]
Biasing is out of scope for Hypothesis, but you can construct a strategy:

    tuples(booleans(), text(), text()).map(lambda ts: (ts[1], ts[2]) if ts[0] else (ts[1], ts[1]))

StackOverflow has a [`python-hypothesis`](https://stackoverflow.com/questions/tagged/python-hypothesis) tag and would be a better forum for this kind of thing.
