### ISSUE TITLE
What should I put into version control?

### ISSUE THREAD

**Issue by apnewberry** [HypothesisWorks/hypothesis-python#1185]
I'm not sure what parts of `.hypothesis/` I should put into version control. Could you please offer some guidance on this? Perhaps a note in the docs too? Thanks!

**Comment by dchudz** [comment]
I think we have recommendations [in the docs](https://hypothesis.readthedocs.io/en/master/database.html): 

> For most users, we therefore recommend using the example database locally and possibly persisting it between CI builds, but not tracking it under version control.

[This](https://hypothesis.works/articles/anatomy-of-a-test/) might also be helpful:

> The database format is safe to check in to version control if you like and will merge changes correctly out of the box, but it’s often clearer to specify the examples you want to run every time in the source code as follows: ...

I think in most cases I would not put `.hypothesis/` in version control at all. It's not guaranteed to retain its information between Hypothesis versions.

**Comment by apnewberry** [comment]
Ah, perfect. Thanks!
