### ISSUE TITLE
[question] builds need random data?

### ISSUE THREAD

**Issue by seospace** [HypothesisWorks/hypothesis-python#1194]
````python
from django.test import override_settings
from django.urls import reverse
from faker.factory import Factory
from hypothesis import given, settings as hyphosettings
from hypothesis.extra.django import TestCase as HyphoTestCase
from hypothesis.strategies import builds

factory = Factory.create()


def get_random_post_data():
    """
    generates data used to register a new user
    """
    password = factory.password()
    return dict(
        email=factory.email(),
        password1=password,
        password2=password,
    )


class UserRegistrationTestCase(HyphoTestCase):

    @given(user_kwargs=builds(get_random_post_data))
    @hyphosettings(max_examples=100)
    def test_register_new_user(self, user_kwargs):
        print(user_kwargs)
````

Why this test runs only once?

**Comment by seospace** [comment]
Obviously it has nothing to do with django, is it desired behaviour to not generate anything if nothing random was passed? I mean, this works:
````
@given(user_kwargs=builds(get_random_post_data, st.integers()))
````

**Comment by Zac-HD** [comment]
Yes, this is working as intended - for tests that depend on the random module, you need to pass the [`random_module`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.random_module) strategy to `@given`.

I'll also note that mixing Hypothesis and Faker doesn't work very well - the idioms and approaches they use aren't really compatible.  Personally, I'd keep any existing tests written with Faker but write new tests using Hypothesis to generate the right type of data, rather than plausible-looking random data.

**Comment by seospace** [comment]
@Zac-HD Can you explain a little more, "I'll also note that mixing Hypothesis and Faker doesn't work very well - the idioms and approaches they use aren't really compatible."

**Comment by Zac-HD** [comment]
- Faker picks random entries from a predefined table of parts (eg "French names").

- Hypothesis generates psudeorandom examples from the strategies you pass to `@given`, using code coverage to choose examples that test ever path through your code.  When it finds a failing example, it "shrinks" to the smallest input that fails with the same error; and it can find multiple distinct errors with a single test.

Faker is designed for filling databases with non-customer information for e.g. load testing; Hypothesis is designed for writing automated tests.

**Comment by seospace** [comment]
@Zac-HD Thank you very much. Looks simple enough. Best of all to you!

**Comment by Zac-HD** [comment]
Happy to help!

**Comment by seospace** [comment]
@Zac-HD Hmmm do you mind to explain how can i perform such trivial tests with hypothesis as testing Django Forms ?
