### ISSUE TITLE
v3.54.0 fails on 32bit windows

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis-python#1207]
See test results: https://ci.appveyor.com/project/conda-forge/hypothesis-feedstock/build/1.0.172

**Comment by DRMacIver** [comment]
@jjgreen This is all in the new complex code. Any ideas?

@Zac-HD I guess we have to turn 32-bit builds back on. :-/

**Comment by jjgreen** [comment]
Ah, looks to be that `hypot()` is not returning exact results, presumably when `sqrt()` is given an integer squared.  A "with relative error 2*eps" would fix that ... I can pick that up.

**Comment by jochym** [comment]
The problem persists ... https://ci.appveyor.com/project/conda-forge/hypothesis-feedstock/build/1.0.173
