### ISSUE TITLE
Adding an iterable strategy

### ISSUE THREAD

**Issue by cdown** [HypothesisWorks/hypothesis-python#135]
Hey there! First of all, thanks for the talk at FB London today. Re: the question I asked about iterables, this is the kind of examples I was thinking of that I said I see a lot (untested, but you get the idea):

``` python
def always_the_same(elements):
    '''Check whether every element in an iterable is the same'''
    if not elements:
        return True
    return all(elements[0] is x for x in elements)
```

In this case, we might have an unindexable type of iterable, so even though this usually works since most people will probably just pass in a list or tuple, it breaks on generators/other non-indexable things. People might still use Hypothesis just to generate a bunch of lists or tuples in this case thinking it is good enough, but if there was a distinct "iterable" class, it could be used except in cases where an indexable iterable was _really_ necessary.

``` python
def yield_twice(elements):
    for item in elements:
        yield item
    for item in elements:
        yield item
```

This is a particularly dumb example, but you get the idea. Mostly I see this when multiple for loops may be used to iterate over something, and the person writing the function didn't consider generator exhaustion.

I think it's worth having an "iterable" strategy just because I think that it's quite possible that when many people say some function "takes an iterable", they may not have considered the consequences of iterables that don't allow indexing, or can become exhausted (just like every Python programmer, I make this assumption without realising it every now and then).

I may take a look at how the scenario generator works and put some code to go with this request, assuming, of course, that my proposal makes sense to you and you think it adds value.

Thanks!

**Comment by DRMacIver** [comment]
Ah, I see, I totally misunderstood what you meant by generator exhaustion, sorry!

This seems like a reasonable thing to have a strategy for. If you want to give it a try I'd be happy to give some guidance.

The approach I would likely take with something like this is that rather than writing a custom strategy I'd just write it as a union of strategies built up from existing ones using the normal combinators. I'd recommend starting there before descending into the guts of how strategies work.

**Comment by untitaker** [comment]
Isn't this, in its simplest form, `def iterable(*a, **kw): return st.lists(*a, **kw).map(iter)`? This returns an iterator that is also an iterable (`iter` appears to be idempotent). It doesn't support indexing and stays exhausted, no matter how often you iterate over it.

    >>> i = iter([1,2,3])
    >>> next(i)
    1
    >>> next(i)
    2
    >>> next(i)
    3
    >>> next(i)
    StopIteration
    >>> i = iter(i)
    >>> next(i)
    StopIteration
    >>> i[0]
    TypeError
