### ISSUE TITLE
Example classification API

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#168]
Quickcheck lets you label examples and then at the end reports a breakdown of the statistics for different labels.

I’ve never got around to implementing this in Hypothesis despite the fact that I’ve been intending to do so since even before 1.0. Part of why is that it matters less for Hypothesis – one of the classic reasons you want this is because Quickcheck can easily generate a lot of duplicate examples if you’re not careful. Hypothesis generally doesn’t do that because of its built in deduplication.

Still, it would be a useful feature which I would like to implement at some point.

**Comment by Zac-HD** [comment]
If this wasn't closed by the `note()` function in Hypothesis 1.14.0, I think it was by the `event()` function in 3.5.0; and #235 and #437 cover the remaining features people have asked for.
