### ISSUE TITLE
Coverage based example discovery

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#169]
The big thing that means that I can’t currently say “Hypothesis is great and you should use it for everything” is that actually for a lot of things you should be using python-AFL instead.

This shouldn’t be the case. Really everything python AFL can do, Hypothesis should be able to do better. It just currently can’t because it’s entirely black box.

Hypothesis should be able to use essentially the AFL algorithm to do this: Instead of just generating examples it generates examples, sees the coverage profile of those, then minimizes down to a seed set for that profile and starts mutating from there.

This would be particularly great in combination with the stateful testing, which has exactly the sort of enormous state space that this sort of concept is great for exploring.

Note: This should be built on top of [Glassbox](https://github.com/DRMacIver/glassbox), which needs work as part of this.

**Comment by Zac-HD** [comment]
Closed by #880 or possibly #861, 🎉 

More work remains of course, but there are and far newer issues addressing specific points we want to improve.
