### ISSUE TITLE
Omit sqlite database implementation when sqlite is not available

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#173]
Some platforms ship the sqlite library separately from core Python (bsd) or don't implement it at all (Jython). This is annoying, because it means Hypothesis doesn't work because it tries to import sqlite3.

This is particularly annoying these days because we don't even really *need* the sqlite implementation.

We could either check for availability and not provide that implementation in that case, or we could just deprecate the silly thing and move on.

**Comment by Zac-HD** [comment]
[The database docs](https://hypothesis.readthedocs.io/en/latest/database.html) suggest that this has been implemented, and that the sqlite3 option may even be removed in future.  If this is not the case, I think we have a docs bug instead.

**Comment by DRMacIver** [comment]
So this has been implemented in the sense that we now don't use sqlite by default, but we still import it unconditionally so things will still break if you don't have it. I'll update the ticket accordingly.

**Comment by Zac-HD** [comment]
It actually looks like it'll be a pretty easy fix to `database.py`, plus some corrections to documentation.  Will we want to start running on Jython in CI?

**Comment by DRMacIver** [comment]
> Will we want to start running on Jython in CI?

Jython support is substantially more complicated than just this one thing, and TBH I'm not sure it's worth it. If someone wants to put in the work to make Hypothesis work on Jython we could certainly start running it in CI, but I'm not sure there's a good reason to.
