### ISSUE TITLE
Provide more generic database API for use in settings

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#175]
Hypothesis in theory has pluggable backends for databases, but the way Settings currently works this isn't really true: You can set a database (and this works a bit like a setting but has all sorts of special cases) and you have the database_file setting that lazily instantiates a database.

There are a couple things going on here:
1. Currently databases have to be lazy loaded due to an explicit dependency on some stuff from search strategy creating a complex nest of dependencies. This is obviously a bad idea. I think this is mostly historical and that the only remaining instance of this is BadData, which should just live in hypothesis.errors in the first place.
2. the database_file parameter can and should be deprecated. The HYPOTHESIS_DATABASE_FILE environment variable should also be deprecated in favour of @Bachmann1234's work on #154. Note: There is not currently a mechanism for deprecating strategies.
3. We can just straight up create a default ExampleDatabase (note that the SQLiteBackend only creates the database on demand anyway) and database can then just be made a normal setting like it should have been from the beginning.

Things to pay attention to:
1. Interaction with #173 for creation of the default example database.
2. What should happen if database_file and database are both specified? Currently this is not an error, but the database will override database_file. Perhaps upgrade to a deprecation warning for now with an InvalidArgument later?

Note: This is quite a large task but contains many individually tractable bits. Work on it can and should be broken up into multiple pull requests.

**Comment by Zac-HD** [comment]
@DRMacIver - I think most of the problems above have been solved since Hypothesis 1.x, and that deprecating `database_file` would be quite straight-forward.  Do you think this is reasonable?

**Comment by DRMacIver** [comment]
> @DRMacIver - I think most of the problems above have been solved since Hypothesis 1.x, and that deprecating database_file would be quite straight-forward. Do you think this is reasonable?

I think this would need to come with more extensive documentation of the database API, but beyond that I don't see any problems.
