### ISSUE TITLE
Bring CouchDB backend into the fold

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#178]
@kxepal has https://github.com/kxepal/hypothesis-couchdb which among other things implements a CouchDB back-end for Hypothesis example storage. This seems like a great idea and it would be nice to have it integrated into core. Not least because the APIs it depends on are not precisely public and I'd like not to break it.

**Comment by Zac-HD** [comment]
https://github.com/kxepal/hypothesis-couchdb hasn't been updated in two years, and is *probably* not compatible anymore.  If it was published on PyPI we could add it to [the list of projects extending Hypothesis](https://hypothesis.readthedocs.io/en/latest/strategies.html); for now though I'll just close the issue.
