### ISSUE TITLE
Hypothesis cannot be installed by `easy_install`

### ISSUE THREAD

**Issue by jerith** [HypothesisWorks/hypothesis-python#184]
Sit back, dear reader, while I tell you a tale of sorrow and software, packaging and pain.

A long time ago, when Python was new and the world was a simpler place, before `pip` roamed the earth, `easy_install` was the way to install packages. Its legacy lives on in `setuptools`, which still uses it in various situations.

Here is what happens when various `setuptools` commands are invoked:

`python setup.py egg_info` creates the `hypothesis.egg-info/` dir and fills it with a tasteful assortment of package metadata.
`python setup.py sdist` builds egg-info, then constructs a source package that contains it along with the code.
`python setup.py bdist_egg` builds egg-info, then constructs an egg zipfile that contains it along with the code.
`python setup.py install` builds egg-info, then constructs an egg zipfile, then installs the egg it just built.
`easy_install hypothesis` downloads the latest source tarball, extracts it, builds an egg zipfile from its contents, and then installs the egg it just built.

The observant among you may have noticed that one of these operations does not build egg-info. It's unnecessary when you're installing a source package, because the source package already contains the egg-info that was built during `python setup.py sdist`.

As mentioned above, when `easy_install` installs a source package, it does so by building an egg and then installing that egg. Specifically, it builds the egg from the contents of the source package and then looks in the location it put the freshly-built egg for a suitable egg to install. _And sometimes it doesn't find one._

Let us now take a brief digression to understand how `setuptools` finds packages to install. Among the various mechanisms is a handler for zipfiles. This explicitly ignores zipfiles that end in `.whl`, because those are wheels. After that, it looks for either egg metadata (in which case it's found an egg) or a directory ending in `.egg` (which it then treats as a potential nested egg and examines further).

In order to build an egg, `setuptools` copies the egg-info and source files to a build dir, compiles the relevant source, and then zips up the build dir and gives the resulting archive a filename ending in `.egg`. Remember that when `setuptools` builds the egg from an sdist, it assumes the egg-info is already in the source tarball.

We now have a condition under which `setuptools` can fail to find an egg it has just built. All one needs is a source package that does not contain egg-info (or does not contain it in the location `setuptools` expects it).

For Hypothesis 1.11.4, `setuptools` expects the tarball to contain `hypothesis-1.11.4/hypothesis.egg-info/PKG-INFO`. What the source tarball actually contains is `hypothesis-1.11.4/src/hypothesis.egg-info/PKG-INFO`. Therefore, the egg it builds during installation lacks the required metadata and is treated as a non-egg zipfile. Installation then fails with a perfectly accurate error message that is completely incomprehensible without knowledge of the above.

The solution here is to make sure that the egg-info gets put in the place `setuptools` expects to find it in the source tarball.

**Comment by DRMacIver** [comment]
So I have no idea what to do about this and can't reproduce the issue myself (that's not to say it's invalid - this is definitely a real bug, but for some reason it works perfectly on my machine).

I also have absolutely no idea about the deep innards of Python packaging. I've read through the documentation and as far as I can tell I'm doing everything correctly here.

So, uh, could somebody save me from packaging hell? Please? :pray:

**Comment by DRMacIver** [comment]
For context: I *could* just ditch the separate src/ directory, but I really really don't want the tests to run in a way that has the hypothesis source directory the path. The fact that they don't has caught multiple bugs in the past. However I am open to suggestions involving changing the project structure .

**Comment by mgedmin** [comment]
A bazillion zope.* packages on PyPI have their sources in src/ and have done so from the very beginning, without any problems with easy_install.

I'm not sure what's happening here.

**Comment by DRMacIver** [comment]
Yeah. What I'm doing is definitely a thing that is supposed to work, and I can't tell what it is I'm doing differently or indeed even what circumstances it doesn't work in..

**Comment by ulope** [comment]
I just compared the structure generated by `python setup.py sdist` from the `zope.interface` package (that also uses a `src` dir) to that of hypothesis and in both cases the `.egg-info` directory is located inside the the `src` subdirectory. 

Additionally I could successfully install both generated .tar.gz packages in fresh virtualenves (Python 2.7 and 3.4) with `easy_install` (setuptools versions tested: 17.0.0 and 18.3.2).

All this would seem to suggest that there is no bug but rather a problem on the OP's system. The usual suspect is an outdated or in other ways broken setuptools installation.

**Comment by DRMacIver** [comment]
Sorry, there's a lot of conversation from IRC that I've now realised didn't make it over here.

Additional details:

1. This seems to be quite consistently experienced by people on OS X (or at least I've had three reports from three different people on OS X experiencing it)
2. It has been seen to happen on the Linux CI server for cryptography.io
3. We've compared setuptools versions and 18.2 (the latest) is consistently being used, even by people for whom it doesn't work.

**Comment by DRMacIver** [comment]
Ah, apparently 18.2 isn't the latest given you just said you were using 18.3.2. But I've seen it working on 18.2 and other people have seen it not working on 18.2

**Comment by ulope** [comment]
Interesting. I'm on OS X too. 

Is there a log or traceback from one of the failing cases?

**Comment by DRMacIver** [comment]
This is from @dstufft trying it on his machine https://bpaste.net/show/beab0f3a4874

I'll see if I can find a log from the cryptography one.

**Comment by DRMacIver** [comment]
Hmm. A thought. @ulope, do you have your file system set to be case sensitive? I wonder if that's the difference?

**Comment by reaperhulk** [comment]
Here's an easy_install failure example (OS X 10.11, Python 2.7.10, setuptools 18.2): https://bpaste.net/show/652ec040c326

**Comment by DRMacIver** [comment]
Thanks @reaperhulk! 

To reconvey discussion from IRC: The problem that the CI server was experiencing is unrelated (it happened when you tried to do easy_install hypothesis-pytest, not hypothesis), so this probably is an OS X specific problem.

**Comment by tdsmith** [comment]
Here's a log with `easy_install -vvv`: (Python 3.5.0, OS X 10.10.5, pip 7.1.2, setuptools 18.3.2)

https://gist.github.com/485613a82f94af5ffabd

You'll see that setuptools invokes bdist_egg, which invokes egg_info: https://gist.github.com/tdsmith/485613a82f94af5ffabd#file-typescript-L158-L160

which seems to contradict the top post.

**Comment by tdsmith** [comment]
Oddly, this works:

```
curl -L https://pypi.python.org/packages/source/h/hypothesis/hypothesis-1.11.4.tar.gz | tar xz
easy_install hypothesis-1.11.4/
```
```
$ pip list
hypothesis (1.11.4)
pip (7.1.2)
setuptools (18.2)
wheel (0.24.0)
```

**Comment by DRMacIver** [comment]
Thanks @tdsmith. Same question as to @ulope. Case insensitive file system?

It's a bit of a long shot, but it's the only plausible thing I can think of that differs between Linux and OS X sometimes but not always.

**Comment by ulope** [comment]
@DRMacIver Yes I use regular case-insensitive HFS+ which has AFAIK always been the default on OS X.

Unfortunately I wasn't able to reproduce the issue on any of the three Macs I currently have access to using various versions of Python and setuptools.

**Comment by DRMacIver** [comment]
Yeah, it's the default, but some people change it and I was wondering if the people for whom it was working on OS X were those who had. I guess that rules out that idea.

**Comment by tdsmith** [comment]
Weird: on OS X, /tmp is a symlink to /private/tmp; that seems to be causing problems.

This works:
```
mkdir tmp
TMPDIR=$PWD/tmp easy_install hypothesis
```

This fails:
```
mkdir -p private/tmp
ln -s private/tmp
TMPDIR=$PWD/tmp easy_install hypothesis
```

I don't know what any of this has to do with hypothesis.

**Comment by tdsmith** [comment]
I'm using a case-insensitive filesystem.

**Comment by jprosevear** [comment]
I have this happening on OSX 10.10 now as well under buildout.

**Comment by chiptip** [comment]
It looks after the egg was built by easy_install, easy_install cannot see the egg even though it was there.

```
$> ls -l /var/folders/ld/ctvjytf14n16djcndqc908zhdnlbf7/T/easy_install-1_pIrS/hypothesis-3.0.2/egg-dist-tmp-CyhnO0
$> hypothesis-3.0.2-py2.7.egg
```

inside of easy_install (20.1.1), in the easy_install.py on [line 1081](https://github.com/jaraco/setuptools/blob/20.1.1/setuptools/command/easy_install.py#L1081), self.run_setup creates the egg, but Environment doesn't return anything in all_eggs, while dist_dir is the directory with the egg.

```
self.run_setup(setup_script, setup_base, args)
all_eggs = Environment([dist_dir])
```

i'm running osx 10.11.3, using python 2.7.10, setuptools (20.1.1) inside of a virtualenv (1.11.6)
