### ISSUE TITLE
Give floats() and decimals() allow_nan and allow_infinity flags.

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#186]
In order to preserve the current behaviour these should default to True. When set to False, the strategies should not generate NaN or infinite values respectively.

A decent first pass at this would be to just use these flags to filter after the existing generation. It would be good to add these flags to the NastyFloats constructor explicitly though.

decimals() can just pass this through to floats() I think.

**Comment by moreati** [comment]
I'm having a go at this, just one design question:

> In order to preserve the current behaviour these should default to True.

If the signature is `def floats(min_value=None, max_value=None, allow_inf=True, allow_nan=True)`, then I think a call like `floats(0, 1000)` becomes self contradictory - `allow_inf==True`, but +/-inf is outside the range specified. Would you be content with `def floats(... allow_inf=None, allow_nan=None)`, plus logic inside to validate on true/false or initialise on None?

**Comment by waynew** [comment]
Personally I think it makes sense to keep the signature and just enforce the constraints at runtime (e.g. raise `ValueError` or something if you have `max_value` and `allow_inf`)

**Comment by moreati** [comment]
> keep the signature ... raise ValueError or something if you have max_value and allow_inf

I presume by singature you mean `def floats(... allow_inf=True ...)`. If so, that would break backward compatibility - since existing calls (e.g. `floats(max_value=10)`) would start defaulting to `allow_inf=True`, and hence raise an exception.

**Comment by DRMacIver** [comment]
@moreati Note that I have just merged https://github.com/DRMacIver/hypothesis/pull/239 which does some of the work.

I think the suggestion of having them default to None and work out the values from the other parameters is a good one though, and I agree that raising an error with contradictory flags is also good (Hypothesis has an InvalidArgument error for that). If you wanted to have a go at adding that I'd be very appreciative. :-)
