### ISSUE TITLE
Document filesystem usage and suitability for .gitignore 

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#201]
See https://github.com/github/gitignore/pull/1516

**Comment by Zac-HD** [comment]
We should just add a sentence to the bottom of https://hypothesis.readthedocs.io/en/latest/database.html , and maybe explicitly give the example of how to ignore `.hypothesis/` and then `!.hypothesis/examples/` if you really really want to share them.
