### ISSUE TITLE
Docs show default for Settings.database_file that is specific to RTD build env

### ISSUE THREAD

**Issue by cdown** [HypothesisWorks/hypothesis-python#202]
http://hypothesis.readthedocs.org/en/latest/settings.html#hypothesis.Settings.database_file

> default value: u’/home/docs/checkouts/readthedocs.org/user_builds/hypothesis/checkouts/latest/docs/.hypothesis/examples.db’

This might be part of a wider issue: ie. defaults might be interpolated by the doc build environment so that they don't make sense any more.

**Comment by DRMacIver** [comment]
Ah, good point. Hm. I'm not sure what to do about that. Maybe the database_file default should be explicitly relative?

**Comment by DRMacIver** [comment]
Fixed by #440
