### ISSUE TITLE
Really large max_size should not try to generate things that large

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#217]
A very large max_size on any of the strategies that support this will often create very large objects. This seems kinda counterintuitive. Specifying a max size should not increase the average size of objects, certainly not to points which cause the tests to slow down horrendously.

Proposed changes:
1. If max_size is > the default average_size, this should not increase the chosen average_size if it is not otherwise specified.
2. average_size + max_size should do something more sensible than it currently does, which is basically to use a mixture of two uniform distributions. It should probably do a capped geometric distribution.

**Comment by Zac-HD** [comment]
The `average_size` parameter now grounds out in [`hypothesis.internal.conjecture.util.many`](https://github.com/HypothesisWorks/hypothesis-python/blob/7c5f242fe723f25a8c2c9ce461584e20c1b4c48d/src/hypothesis/internal/conjecture/utils.py#L353-L402).  In all cases it is defined as the *minimum* of twice the min_size, the midpoint of min and max sizes, and a constant (which varies between strategies).

Increasing max size above ten does not increase the average size.
