### ISSUE TITLE
Fix math typo in BinaryTreeStrategy example

### ISSUE THREAD

**Issue by fritzo** [HypothesisWorks/hypothesis-python#224]
Expected: `split_location` should be drawn from some interval [0+epsilon, 1-epsilon]
Actual: `split_location` is drawn from the interval [0.2, 1.0]
Location: https://github.com/DRMacIver/hypothesis/blob/master/examples/bintree.py#L149
Patch:

<pre>
             # stacks, we force this not to go too far to the edges so as to
             # keep the depth under control.
-            split_location=0.2 + 0.8 * random.random(),
+            split_location=0.1 + 0.8 * random.random(),
 
             # We need a parameter to control the shape of our leaf distribution
</pre>

**Comment by DRMacIver** [comment]
I don't think this is a typo? The comment explains that the purpose of this is to keep the tree depth under control, which needs to keep the parameter away from zero, not 1.

Why do you think it is one?

**Comment by DRMacIver** [comment]
Sorry. You're quite right. I shouldn't reply to issues before coffee :-)

**Comment by alexwlchan** [comment]
Closing, as this patch refers to an example script that was deleted nearly eleven months ago in the cleanup for v2.0 (7712c01).
