### ISSUE TITLE
one_of and | should flatten branches

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#234]
So if I do something like one_of(a, one_of(b, c)) this should be the same as one_of(a, b, c).

This is particularly important for use of |.

...especially because I've been telling people for months that it _does_ do this.

**Comment by Daenyth** [comment]
Is this something relatively easy? I might take a swing at it since I use `|` all over

**Comment by DRMacIver** [comment]
It's probably quite approachable, yes.

The implementation strategy I had in mind was to add a 'branches' (or some similar name) property to strategy and have the underlying function both one_of and | call flatten out branches when creating the relevant strategy.

You'd then need to propagate this through [deferred strategies](https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/searchstrategy/deferred.py), and it would probably make sense to also propagate it through map and filter (and maybe flatmap for the left hand side) so that e.g. (x | y).map(f) | z is equivalent to one_of(x.map(f), y.map(f), z)

If you're interested I'd definitely encourage you to give it a go, and I'm happy to answer any questions you might have about details.

**Comment by Daenyth** [comment]
Follow up to that, do you have any kind of strategy benchmarking setup so that I can profile that changes I make improve runtime speed?

**Comment by DRMacIver** [comment]
They're a bit neglected and not that easy to use, but there are [these ones](https://github.com/HypothesisWorks/hypothesis-python/blob/master/benchmarks/test_strategies.py) using [pytest-benchmark](https://github.com/ionelmc/pytest-benchmark).

I'd probably be more interested in the distribution of data here though, so you might want to add something to [the statistical distribution tests](https://github.com/HypothesisWorks/hypothesis-python/blob/master/tests/nocover/test_statistical_distribution.py). The idea of these is that you give them some strategy and some condition and specify a minimum fraction of the time you want the condition to be satisfied.

**Comment by DRMacIver** [comment]
To clarify the problem on distribution: The problem is that right now a | (b | c) will draw from a 50% of the time and b and c 25% of the time (sortof. It's actually more complicated than that in a way that will probably bias it away from that in favour of a and c, but to a first approximation that's true). It would be nice if they were each closer to 1/3 of the time.

**Comment by alexwlchan** [comment]
I think this is fixed by #406, no?

**Comment by Zac-HD** [comment]
@DRMacIver - previously resolved.

**Comment by DRMacIver** [comment]
Confirmed, thanks.
