### ISSUE TITLE
Move @fails annotation into main test decorators

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#24]
I was reading "Software Testing with Quickcheck" by John Hughes and in it he points out that keeping around failing properties with a marker that they fail is actually a useful thing which people should do as part of their test suites. This seems like an eminently fair point. I already have something like this in the tests for my test decorators. It currently depends on py.test but could easily be made not to. Do this and merge it into the main API.

**Comment by Zac-HD** [comment]
See [`test.common.utils.fails_with`](https://github.com/HypothesisWorks/hypothesis-python/blob/172ccb8155166b77424c6253ce24aa0f14def666/tests/common/utils.py#L58-L68); I'm also adding a similar decorator for "this test is for a deprecated thing" as part of #599.

**Comment by DRMacIver** [comment]
I think this issue was actually about making fails part of the public API, but I don't think this was ever a good idea and people should be using pytest's xfail or equivalent for it really (maybe we should too)

**Comment by Zac-HD** [comment]
Ah, right.  I agree that it's a separate concern to the rest of the Hypothesis API, but it's still useful for our own tests.

**Comment by DRMacIver** [comment]
Yup. It's perfectly sensible to have extra decorators like this internally and/or in the test helpers, just not part of the public API. Past-@DRMacIver had some odd ideas about API design which I've had to unlearn the hard way. :-)

**Comment by Zac-HD** [comment]
> people should be using pytest's xfail or equivalent for it really (maybe we should too)

For posterity: `@pytest.mark.xfail(raises=FooError)` semantically different to `@fails_with(FooError)` - the former indicates that this is expected behaviour due to an unfixed bug (and the test is reported as xfailed rather than passed), while the latter indicates that the test *should* raise FooError to pass.  Our internal decorator is more like a decorator form of `with pytest.raises(FooError): ...`.
