### ISSUE TITLE
Old-style classes probably generate unhelpful repr's in various places

### ISSUE THREAD

**Issue by Julian** [HypothesisWorks/hypothesis-python#240]
There are a few places that use `type(Thing())` -- for old style classes, this will be `classobj`, not `Thing` so doing things to that, especially using its name, won't produce much. See for example `splat` inside `hypothesis.strategies.build`.

`Thing().__class__.__name__` will be more correct (it will return `Thing` even for old-style classes), but then non-instances of classes would also need to be handled (e.g. an old-style class itself will have no `__class__`.)

Probably copying some things from `twisted.python.reflect` will make not needing to implement this again a bit less annoying.

**Comment by Zac-HD** [comment]
Do you know of any logic errors that this may cause?  If it's a purely cosmetic issue, I'll close the issue - to avoid `classobj`, just use new-style classes.

**Comment by Julian** [comment]
That's not always possible :) but yeah I'm pretty sure this should just be
cosmetic, it makes things like what Hypothesis prints out as the examples
it's trying not be useful whenever there's an old style class involved.
Feel free to close though if there isn't a chance this'll be looked at, I
doubt I'll get time to do so myself.

**Comment by DRMacIver** [comment]
I think the printing out of examples should work fine with old style classes FWIW - we use something quite different for that (it's a vendored version of IPython's pretty printing) - it's just reprs of strategies that don't work.

But yeah I think it's safe to say that although this is a bug it's probably not ever going to get fixed unless someone external is really motivated.
