### ISSUE TITLE
`IOError` on `import hypothesis.strategies`

### ISSUE THREAD

**Issue by rmoehn** [HypothesisWorks/hypothesis-python#242]
I'm running Hypothesis in a Docker container. On the first run, everything works fine. One the second run I get this:

```python-traceback
Traceback (most recent call last):
[…]
  File "[my_test].py", line 18, in <module>
    import hypothesis.strategies as st
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/strategies.py", line 71, in <module>
    @defines_strategy
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/strategies.py", line 51, in defines_strategy
    @proxies(strategy_definition)
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/internal/reflection.py", line 497, in accept
    copy_argspec(target.__name__, getargspec(target))(proxy)))
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/internal/reflection.py", line 465, in accept
    u'invocation': u', '.join(invocation_parts)
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/internal/reflection.py", line 372, in source_exec_as_module
    f = open(temporary_filepath, u'w')
IOError: [Errno 2] No such file or directory: u'/.hypothesis/eval_source/hypothesis_temporary_module_9abd2800900986980ad8f68a32f0005fc05800d8_53a57e8c-7a3a-4e9a-9a0c-8a8641d521d4.py'
```

The immediate cause of the `IOError` appears to be that Hypothesis tries to create a directory directly beneath `/`. This has to do with my setup, so I don't blame you. My concern is that Hypothesis tries to create a directory somewhere in the file system on module load. This strikes me as unorthodox.

Specifically, [`hypothesis_home_dir()`](https://github.com/DRMacIver/hypothesis/blob/v1.13.0/src/hypothesis/settings.py#L51) creates a `.hypothesis` directory either under a directory specified by the undocumented environment variable `HYPOTHESIS_STORAGE_DIRECTORY` or under the current working directory. The latter case is what ultimately causes the above exception. The former case I now use to redirect the `.hypothesis` creation to some other place. This, however, is a nasty workaround.

**Comment by DRMacIver** [comment]
Hm, yes, the behaviour when cwd is root isn't great.

Creating a directory on module load is indeed unfortunate. There are semi-good reasons (or, at least, probably unavoidable ones) for that, but it would be nice not to.

I'm rather surprised everything works on the first run. What's different there?

**Comment by rmoehn** [comment]
I don't know. For now, I didn't manage to make a minimal example, either. Maybe later.

I guess there are also reasons that `.hypothesis` can't be a temporary directory? I expect it's about the example database.

**Comment by DRMacIver** [comment]
It's partly about the example database, partly that if you try to clean up the generated files on exit it breaks coverage so you'll end up spamming /tmp/ with new directories.

**Comment by rmoehn** [comment]
However the reasons, there should be documentation and a proper exception text in order to lessen the suprise for the users. If you want, I could contribute that, but I'm not planning to make more contributions unless I find another itch.

As to why it works the first time and not the second: (found this rather stupid quirk after some tries at building a minimal example) when I run a fresh container, it starts out in `/var/lib/something`, but on subsequent runs it's in `/`, where the user doesn't have write permission anymore. Don't know why the directory change; I haven't built it.

**Comment by Zac-HD** [comment]
Proposed solution:

- document creation of this directory and where it goes
- document the environment variable
- delay creating the directory until it's actually going to be used (so eg an in-memory example database doesn't touch the file system)
- give a more useful error if it fails anyway

**Comment by Zac-HD** [comment]
#767 (or a very closely related bug) can be caused by a similar problem, where files can't be written at runtime.

I think we should handle this case, and test that hypothesis works on a read-only filesystem.  Obviously this precludes saving examples, but everything else should be possible.
