### ISSUE TITLE
Documentation for hypothesis.extra.numpy

### ISSUE THREAD

**Issue by honnibal** [HypothesisWorks/hypothesis-python#259]
Hi,

I started using Hypothesis recently, and had one of those "where have you been all my life" moments. I expect I'll be using it heavily, and instructing my team in how to use it.

Currently the `hypothesis.extra.numpy` module is undocumented. I assume you're open to contributions in this respect? How do you feel about documentation changes that aren't necessarily "good", but are at least "better"? For instance it's possibly better for the docs to at least _mention_ the module, even if the documentation for it isn't necessarily good.

Thanks for your work,
Matt
spacy.io

**Comment by DRMacIver** [comment]
Huh, you're right. I could have sworn it was documented in the extra packages, but it's not.

I'm definitely up for documentation PRs, even if they're imperfect. I'll probably offer feedback and ask you to change some things, especially if anything is actually wrong, but it doesn't have to be a work of great literature or anything :-)

**Comment by honnibal** [comment]
Great.

Does this look like it represents reasonable usage?

```python
from hypothesis import given, assume
from hypothesis.strategies import lists, integers, floats
from hypothesis.extra.numpy import arrays


def lengths(lo=1, hi=10):
    return integers(min_value=lo, max_value=hi)


def ndarrays_of_shape(shape, lo=-1000.0, hi=1000.0):
    return arrays('float32', shape=shape, elements=floats(min_value=lo, max_value=hi))
    

def ndarrays(min_len=0, max_len=10, min_val=-10000000.0, max_val=1000000.0):
    return lengths(lo=1, hi=2).flatmap(
        lambda n: ndarrays_of_shape(n, lo=min_val, hi=max_val))


def positive_ndarrays(min_len=0, max_len=10, max_val=100000.0):
    return ndarrays(min_len=min_len, max_len=max_len, min_val=0, max_val=max_val)


def negative_ndarrays(min_len=0, max_len=10, min_val=-100000.0):
    return ndarrays(min_len=min_len, max_len=max_len, min_val=min_val, max_val=-1e-10)
```

Ultimately what I'll want are three ndarrays such that I have an M*N matrix, an array of length M, and an array of length N. This seems to match to the docs example of `flatmap` fairly well. I'll draw a tuple of lengths, and then use flatmap as above.

The positive/negative etc helpers are there because I figure I'll want tests where I specifically probe the behaviour given values of a certain sort.

**Comment by caichinger** [comment]
Hi,

like @honnibal , I was searching for documentation on `extra.numpy` and based on your discussion I decided to submit #309 providing a few basic examples.

Maybe you two want to take a look.

Very interesting library! :)

**Comment by Zac-HD** [comment]
@DRMacIver - previously resolved.

**Comment by DRMacIver** [comment]
So it has been. Thanks.
