### ISSUE TITLE
Composite strategy doesn't copies keyword-only arguments

### ISSUE THREAD

**Issue by kxepal** [HypothesisWorks/hypothesis-python#290]
```
>>> import hypothesis
>>> from hypothesis.strategies import composite
>>> @composite
... def func(draw, *, kwarg): pass
>>> func(kwarg=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: func() got an unexpected keyword argument 'kwarg'
```

And it seems true:

```
>>> import inspect
>>> inspect.getargspec(func)  # nothing good
ArgSpec(args=[], varargs=None, keywords=None, defaults=None)
```

Meanwhile:

```
>>> @composite
... def func2(draw, *, kwarg, **rest): pass
>>> func2(kwarg=1)  # ok
```

Let's try a simpler case:

```
>>> def cnuf(*, kwarg): pass
... 
>>> inspect.getargspec(cnuf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/inspect.py", line 1045, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
>>> inspect.getfullargspec(cnuf)
FullArgSpec(args=[], varargs=None, varkw=None, defaults=None, kwonlyargs=['kwarg'], kwonlydefaults=None, annotations={})
```

Aha! So `inspect.getargspec` cannot see keyword-only arguments. And suddenly `composite` strategy [uses](https://github.com/DRMacIver/hypothesis/blob/3.0.4/src/hypothesis/strategies.py#L774) it for introspection.

Would it be safe to replace `getargspec` with `getfullargspec`?

**Comment by DRMacIver** [comment]
Ah, yes, it's likely that most of Hypothesis's function introspection code is broken in this manner. given will probably also swallow keyword only arguments.

This is probably quite involved to fix, but definitely should be.

**Comment by DRMacIver** [comment]
RE using getfullargspec: The correct solution is probably to use an inspect.signature backport, as all of the argspec machinery is deprecated and will be gone in 3.6

**Comment by Zac-HD** [comment]
Still present in Hypothesis `3.7.0`.  #293 will also require some argspec introspection, which may provide some useful experience.

**Comment by DRMacIver** [comment]
Yeah. This isn't going to be fixed without Some Work and probably requires a fairly major re-engineering of how the internals for argument handling work. I confess I've been putting it off.

**Comment by Zac-HD** [comment]
Turns out that [`inspect.getfullargspec` is *not* deprecated](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec) in 3.6, "in order to restore a clearly supported standard interface for single-source Python 2/3 code migrating away from the legacy getargspec() API"  - exactly our situation.

Of course, we'll still want to squash the deprecation warning when running under 3.5...

**Comment by kxepal** [comment]
Hooray! Thank you all!

**Comment by Zac-HD** [comment]
You're welcome!  Some of the underlying problems have been annoying me too, and it's always satisfying to widen the gap between Py2 and Py3 a bit more 😉
