### ISSUE TITLE
idea for better django support

### ISSUE THREAD

**Issue by ZabelTech** [HypothesisWorks/hypothesis-python#299]
hi,

i used this library for the first day and I have a little improvement. I like how 
 it supports generation out of Django models. Here is what i found usefull in my own tests:

```
def gen(model, **dct):
    dct = {k: just(v) if not hasattr(v, '__iter__') \
           else one_of(map(lambda x: just(x), v)) \
           for (k,v) in dct.iteritems()}
    return models(model, **dct)
```

and then i wrap it for a specific model, like this:

```
def c_gen(dct):
    return gen(Card, dct)
```

and then i can wrap my tests with this:

`@given(c_gen(active=False))`

I know, this does not take ForeignKeys and parameters, that are allready given as a strategy, into account.
But I think this does really improve readability and condenses everything what is important to the test right to it. I have some more ideas, mostly from using clojure/test.check.

Are you interested in Pull Requests?

**Comment by Zac-HD** [comment]
See [CONTRIBUTING.rst](https://github.com/HypothesisWorks/hypothesis-python/blob/master/CONTRIBUTING.rst) - we're definitely interested in pull requests, but you'll need to explain the design and usefulness of the API as well as providing an implementation.

As it's been more than a year, I'm going to close the issue.
