### ISSUE TITLE
Tests for packaging

### ISSUE THREAD

**Issue by DamienCassou** [HypothesisWorks/hypothesis-python#300]
In https://github.com/DRMacIver/hypothesis/blob/master/docs/packaging.rst#testing-hypothesis, you explain how to run tests. Just executing `py.test` seems to run everything which takes ages (especially benchmarks). Could you please tell us which subset is meaningful? Thanks

**Comment by The-Compiler** [comment]
[packaging.rst](https://github.com/DRMacIver/hypothesis/blob/master/docs/packaging.rst) has some words on this, and you might want to read it either way if you're going to package hypothesis :wink:

**Comment by untitaker** [comment]
@The-Compiler He did link the same page above. :P

**Comment by The-Compiler** [comment]
Whoops, sorry! :blush: 

It seems to me like `cover` is the recommended subset to run though.

**Comment by Zac-HD** [comment]
It's been more than a year, so I'm going to close this.  If it's not addressed, feel free to reopen!
