### ISSUE TITLE
Dropping into pdb session within decorated test captures Ctrl-C

### ISSUE THREAD

**Issue by schinckel** [HypothesisWorks/hypothesis-python#316]
I was debugging a test, and I inserted a `import pdb; pdb.set_trace()` statement. When I used Ctrl-C, it seems that something was capturing it, and not passing it up the chain: I was unable to quit the test running with repeated Ctrl-C presses.

The only way to escape was to Ctrl-Z and then manually kill the process by PID.

This is running within a django test (using unittest test runner).

**Comment by DRMacIver** [comment]
Huh.

Are you sure this is something on the Hypothesis end rather than something else in your toolchain? I'm not certain it's not, but I use pdb a lot and I've never noticed a problem, and Hypothesis generally tries not to catch interrupts.

**Comment by schinckel** [comment]
Hmm. I'll look deeper.

**Comment by DRMacIver** [comment]
Well, I'm definitely not saying this isn't a Hypothesis bug! You should feel free to reopen / leave it open until you're sure. I'm just saying that I'm surprised by this information.
