### ISSUE TITLE
Missing git tag for 3.4.0 release

### ISSUE THREAD

**Issue by felixonmars** [HypothesisWorks/hypothesis-python#324]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by DRMacIver** [comment]
Ack. Sorry, so there is. It wasn't even a case of forgetting to push it, I just flat out failed to create this one! Another :+1: for getting around to making Travis do my releases from tags I guess.

Thanks for the catch. Fixed now.

**Comment by felixonmars** [comment]
Thanks for the really quick fix :D
