### ISSUE TITLE
HealthCheck.exception_in_generation should include the exception.

### ISSUE THREAD

**Issue by Wilfred** [HypothesisWorks/hypothesis-python#340]
Currently, the `FailedHealthCheck` message does not include the exception message. Instead, it just has the generic:

> FailedHealthCheck: An exception occurred during data generation in initial health check. This indicates a bug in the strategy. This could either be a Hypothesis bug or an error in a function you've passed to it to construct your data. See http://hypothesis.readthedocs.org/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.exception_in_generation to the suppress_health_check settings for this test.

This was a test depending on an old keyword argument to a strategy we'd written. It would be really helpful if hypothesis reported the exception that occurred.

**Comment by DRMacIver** [comment]
The exception does get printed, though I agree that it should be in the health check error message too. Are you not seeing the stack trace and message from the original at all or were they just 
buried in test noise somewhere? If the former I wonder what's swallowing them. :-( What test runner are you using?

**Comment by Wilfred** [comment]
I'm using py.test as my test runner, with its JUnit XML output being shown on Jenkins.

Looking at the raw console logs, you're absolutely right: there's a `--- Hypothesis ---` section with the full traceback. It's not in the individual test output on Jenkins though (which is odd, because Jenkins usually picks up stdout on individual tests).

Nonetheless, it would probably be useful to at least have the exception's class and `.message` in the `FailedHealthCheck` message.

**Comment by DRMacIver** [comment]
Yeah, I agree including it in the message is a good idea. I just wanted to make sure something mysterious wasn't going on.

The message is probably being printed to stderr. Maybe that's why Jenkins isn't picking it up?

**Comment by Zac-HD** [comment]
Closed by #970.
