### ISSUE TITLE
usage in combination with xdist fails on windows due to posix style atomic file rewrite

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [HypothesisWorks/hypothesis-python#344]
on pytest-dev/pytest#1705 we see 

```
_________________ ERROR collecting testing/python/metafunc.py _________________
_pytest\python.py:374: in fget
    return self._obj
   AttributeError: 'Module' object has no attribute '_obj'
During handling of the above exception, another exception occurred:
...
.tox\py35-xdist\lib\site-packages\hypothesis\internal\charmap.py:77: in categories
    cm = charmap()
.tox\py35-xdist\lib\site-packages\hypothesis\internal\charmap.py:63: in charmap
    os.rename(tmpfile, f)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\projects\\pytest\\.hypothesis\\tmp\\tmp9lzkh68w' -> 'C:\\projects\\pytest\\.hypothesis\\unicodedata\\8.0.0\\charmap.pickle.gz'
_________________ ERROR collecting testing/python/metafunc.py _________________
```

**Comment by DRMacIver** [comment]
Yes, it looks like you're right. Sigh.

Atomic file creation turns out to be a hard problem.

**Comment by DRMacIver** [comment]
...but not that hard. I was just doing it wrong.

I've got a probably fix. Just letting CI run. Assuming it works I'll do a patch release for the issue later today.

**Comment by RonnyPfannschmidt** [comment]
\o/ thanks for the swift response :+1:

**Comment by DRMacIver** [comment]
No problem. It's proving a little fiddlier than I thought though (mostly because consistent behaviour between Python 2 and 3). Hopefully will still have a fix out today. Might be tomorrow.

**Comment by DRMacIver** [comment]
And then everything went smoothly. So 3.4.1 is now out. Please test and let me know if you're still experiencing this problem.
