### ISSUE TITLE
Allow `unique_by` strategy kwargs to accept a list of callables

### ISSUE THREAD

**Issue by Daenyth** [HypothesisWorks/hypothesis-python#361]
This would be really handy; I have a case where I need to generate a list that's unique across two axis. As it stands, I have to use `unique_by=first_axis` plus `assume(lambda xs: len(map(snd_axis, xs)) == len(set(map(snd_axis, xs))))` which is leading to me getting `Unsatisfyable` failures

**Comment by Zac-HD** [comment]
I might be misunderstanding what you're trying to do - it sounds like you're trying to generate a length-n list of length-m lists, such that there are no shared elements among the inner lists.  If so, why not generate a single larger list and then chop it up into smaller lists?

I implementing this inside Hypothesis wouldn't actually make it any more efficient, but if you were trying to do something else feel free to reopen the issue - and please post a demonstration strategy we can run and ideally an example of the data to generate.
