### ISSUE TITLE
Py3.4: Function has keyword-only arguments or annotations, use getfullargspec()

### ISSUE THREAD

**Issue by Tinche** [HypothesisWorks/hypothesis-python#363]
My pytest test function has an annotated parameter (https://github.com/Tinche/cattrs/blob/master/tests/test_loads.py#L99).

```
tests/test_loads.py:99: in <module>
    def test_loading_primitives(converter: Converter, primitive_and_type):
.tox/py34/lib/python3.4/site-packages/hypothesis/core.py:151: in run_test_with_generator
    original_argspec = getargspec(test)
/opt/python/3.4.2/lib/python3.4/inspect.py:930: in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
E   ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```
Just use getfullargspec for 3.4 too? It works on 3.5.

**Comment by DRMacIver** [comment]
Oh, how annoying.

I'll see about fixing this. it's probably not hard, but getting these things to work consistently across 2 and 3 has been a nightmare :-/ 

Can you elaborate on the use case here? I assume working but stripping the annotation would be bad, or would you not care?

**Comment by Tinche** [comment]
Well, I mostly annotate the arguments to get autocomplete in PyCharm. Not sure how programatically stripping the annotations would affect it, probably not much.

**Comment by DRMacIver** [comment]
Hmm. So this is to get auto completion in code you're writing within the test body? That's probably fine then - if auto completion works now I don't imagine it would stop working if I fixed this issue but didn't preserve annotations.

**Comment by Tinche** [comment]
Correct.

**Comment by DRMacIver** [comment]
OK. That makes life easier. I'll try to get a fix out soon that works but strips the type annotations from the end result.

Long-run there's a big rework due here to use signature() that would also be needed to fix [Issue 290](https://github.com/HypothesisWorks/hypothesis-python/issues/290). When that happens preserving annotations should become better supported, but in the short run there's no reason not to pick the low hanging fruit.

**Comment by Tinche** [comment]
*cough*drop2.7*cough*

Thanks for your great work on Hypothesis ;)

**Comment by DRMacIver** [comment]
> coughdrop2.7cough

I'm counting down the days till 2020.

**Comment by Tinche** [comment]
🎉 !

❤️

**Comment by Zac-HD** [comment]
For posterity (ie people arriving via Google), we have since gone the other way in #625 and now use `inspect.getfullargspec` or a shim to preserve annotations and other Python3-only features.
