### ISSUE TITLE
Stats for stateful tests?

### ISSUE THREAD

**Issue by Tinche** [HypothesisWorks/hypothesis-python#365]
Hi,

the new statististics feature looks really nice and useful. It is supposed to work with stateful tests? I'm not seeing any output.

**Comment by DRMacIver** [comment]
I, err, may have completely forgotten about stateful tests when writing this feature. Oops.

Fortunately it's not hard to fix. I'll have a fix out in the next patch release.

**Comment by Tinche** [comment]
Thanks!

**Comment by Tinche** [comment]
I'm not familiar with the implementation, just a note: can we make it work with run_state_machine_as_test too?

**Comment by DRMacIver** [comment]
> I'm not familiar with the implementation, just a note: can we make it work with run_state_machine_as_test too?

Hmm. Not easily in a way that is generally correct, no. :-(

If you want a cheesy workaround that isn't part of the official API but will basically continue to work forever, you can set "my_test_case.is_hypothesis_test = True" and it will start working, though that will assume you only use run_state_machine_as_test once in the test (or rather will ignore all but the last)

**Comment by Tinche** [comment]
Roger that. I do call run_state_machine_as_test only once. The reason I'm using it is so I can prepare strategies used in the state machine class, using fixtures.

 The problem is there's nothing to let Hypothesis know a given test function is a Hypothesis test, if using run_state_machine_as_test?

**Comment by DRMacIver** [comment]
Yeah, that. Also that you don't want a test to get statistics just because e.g. it happens to use find() inside it, which is the main reason why this isn't turned on for all tests.

**Comment by Tinche** [comment]
Right. I can make a decorator for myself and use that.
