### ISSUE TITLE
Stateful: print steps when verbose, even when non failing

### ISSUE THREAD

**Issue by Tinche** [HypothesisWorks/hypothesis-python#370]
Hi,

when a stateful test fails, Hypothesis will print out a helpful log of steps taken: 
```
Step #1: create_new_player(udid='00000000000000000000000000000000')
Step #2: facebook_connect(choice=choice)
Choice #1: 'Mqylr105'
Step #3: invite_nonexisting(rnd=RandomWithSeed(0), choice=choice)
```
I'm saying this would be useful in normal operation too. By normal operation, I mean just general output generated while the tests are running.

If I set `HYPOTHESIS_VERBOSITY_LEVEL` to verbose, I see output like ```Trying example <hypothesis.stateful.StateMachineRunner at 0x10cd9fb00>``` but this is obviously much less useful than nicely formatted steps. My tests generate a lot of logs so it's difficult to track what exactly's going on.

**Comment by DRMacIver** [comment]
If you set the level to "debug" instead of verbose you'll get this. I'm open to changing that behaviour so that it happens on verbose as well though, as debug also contains a bunch of Hypothesis internal stuff you probably don't care about.

**Comment by Tinche** [comment]
Thanks, I can just grep for the time being. I'd still say it'd be useful to have this in verbose, I find this information interesting.

**Comment by Tinche** [comment]
I'm gonna close this, feel free to reopen if you want a reminder :)
