### ISSUE TITLE
Appveyor builds aren’t running against pull requests

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis-python#384]
Looking at the CI runs on #383, I only have results for Travis, which covers Linux and OS X. There’s Appveyor config in the repository root, but it doesn’t seem to be running against pull requests. Should it be?

(I ask because I’m looking at a bug that only affects Linux OSes, so there’s at least some OS-dependent behaviour lurking in Hypothesis.)

**Comment by DRMacIver** [comment]
What's particularly weird is that they *are* running on pull requests but they're not showing up as statuses. See https://ci.appveyor.com/project/DRMacIver/hypothesis/history <- all your work in the PR is showing up there, it's just not making it to the PR status check. I don't know why.

**Comment by alexwlchan** [comment]
Did you start doing Appveyor runs before you migrated to the HypothesisWorks organisation?

I wonder if it's trying to post statuses to DRMaciver/hypothesis, and failing because no such repo exists.

**Comment by DRMacIver** [comment]
I did, and it did indeed break when I migrated it over, but I'm pretty sure I've fixed that and it has been working.

**Comment by DRMacIver** [comment]
Hmm. I can't actually find any evidence of the claim that it has been working. The builds have been running, so maybe that conned me into thinking it was.

**Comment by DRMacIver** [comment]
I'm going to try deleting and recreating the project and see if that fixes it. It'll lose the build history, but ¯\_(ツ)_/¯. I'm not very attached to that.

**Comment by DRMacIver** [comment]
OK. I *think* it should be working now. It looks like it had picked up the project move but I had never actually granted it API access to the HypothesisWorks organisation, so it was running the builds but unable to actually push status updates. Push something to your branch and see if that works?

**Comment by alexwlchan** [comment]
Yep, I see Appveyor builds now in the status checks now. Hooray!

**Comment by alexwlchan** [comment]
For extra brownie points, we should probably make Appveyor builds a required check for merging pull requests. Right now it’s just Travis, and we shouldn’t punish Windows users. :-)

**Comment by DRMacIver** [comment]
Mmm. Brownies.

(It is done)
