### ISSUE TITLE
Problem with Makefile: No module named pip

### ISSUE THREAD

**Issue by jreinhardt** [HypothesisWorks/hypothesis-python#399]
Hi,

while working on https://github.com/HypothesisWorks/hypothesis-python/pull/393 I hit a problem with running the formatting checks, the test suite or anything powered by the makefile.

I am on Debian Jessie, with python2.7.9, python 3.4.2 and the corresponding pips installed via the package manager.

It seems to be a problem with pip or the environment, here the console output for the last retry of  `make check-py27`, other targets give similar results:

```
+ env
+ grep UTF
LC_ALL=en_US.UTF-8
+ BASE=/home/jreinhardt/.cache/hypothesis-build-runtimes
+ mkdir -p /home/jreinhardt/.cache/hypothesis-build-runtimes
+ LOCKFILE=/home/jreinhardt/.cache/hypothesis-build-runtimes/.install-lockfile
+ true
+ mkdir /home/jreinhardt/.cache/hypothesis-build-runtimes/.install-lockfile
+ echo 'Successfully acquired installer.'
Successfully acquired installer.
+ break
+ trap 'rm -rf /home/jreinhardt/.cache/hypothesis-build-runtimes/.install-lockfile' EXIT
+ PYENV=/home/jreinhardt/.cache/hypothesis-build-runtimes/pyenv
+ '[' '!' -d /home/jreinhardt/.cache/hypothesis-build-runtimes/pyenv/.git ']'
+ back=/home/jreinhardt/sources/hypothesis-python
+ cd /home/jreinhardt/.cache/hypothesis-build-runtimes/pyenv
+ git fetch
+ git reset --hard origin/master
HEAD is now at 53cf2e3 Merge pull request #765 from takeru/anaconda3-4.2.0
+ cd /home/jreinhardt/sources/hypothesis-python
+ SNAKEPIT=/home/jreinhardt/.cache/hypothesis-build-runtimes/snakepit
+ for var in '"$@"'
+ case "${var}" in
+ install 2.7.11 python2.7
+ VERSION=2.7.11
+ ALIAS=python2.7
+ mkdir -p /home/jreinhardt/.cache/hypothesis-build-runtimes/versions
+ SOURCE=/home/jreinhardt/.cache/hypothesis-build-runtimes/versions/python2.7
+ '[' '!' -e /home/jreinhardt/.cache/hypothesis-build-runtimes/versions/python2.7 ']'
+ rm -f /home/jreinhardt/.cache/hypothesis-build-runtimes/snakepit/python2.7
+ mkdir -p /home/jreinhardt/.cache/hypothesis-build-runtimes/snakepit
+ /home/jreinhardt/.cache/hypothesis-build-runtimes/versions/python2.7/bin/python -m pip.__main__ install --upgrade pip wheel virtualenv
/home/jreinhardt/.cache/hypothesis-build-runtimes/versions/python2.7/bin/python: No module named pip
+ rm -rf /home/jreinhardt/.cache/hypothesis-build-runtimes/.install-lockfile
Command failed. Retrying...
Command failed five times. Giving up now
Makefile:40: recipe for target '/home/jreinhardt/.cache/hypothesis-build-runtimes/snakepit/python2.7' failed
```

Any ideas?

**Comment by DRMacIver** [comment]
My guess is that the problem comes from the makefile's use of pyenv for managing its python versions and it's probably building a python then unable to install pip due to missing modules. 

The suggested pyenv dependencies are 
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils

Try installing those and doing a make clean them trying again? 

If that is the problem then the makefile should definitely handle this better

**Comment by jreinhardt** [comment]
No, this doesn't help.

**Comment by jreinhardt** [comment]
I don't know how it is supposed to look, but the install script sees the following PATH:

`/home/jreinhardt/.cache/hypothesis-build-runtimes/snakepit:/home/jreinhardt/.cache/hypothesis-build-runtimes/tools:..`

**Comment by DRMacIver** [comment]
The makefile isn't using most of the pyenv machinery, only the pyenv-build plugin.

If there's nothing in the snakepit directory that's a bit weird. Can you try and find out somehow what Python it *is* running there? It sounds like it must be the system Python but I wouldn't have expected that to be possible.

**Comment by jreinhardt** [comment]
Ok, installing the dependencies, deleting .cache/hypothesis-build-runtimes and then running the makefile again fixed it. It seems an old python from times where pip could not be built was still lying around in the hypothesis-build-runtimes/version directory, and was being used.

It works now. Thanks

**Comment by DRMacIver** [comment]
Ah, huh. Sorry, I expected clean to delete those.

I'll open a new bug that this should fail more gracefully.
