### ISSUE TITLE
No tag for version 3.6.1

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis-python#412]
I see the new version on PyPI:

https://pypi.python.org/pypi/hypothesis/3.6.1

but no tag on GitHub:

https://github.com/HypothesisWorks/hypothesis-python/releases

**Comment by DRMacIver** [comment]
Argh. Fixed now.

Me not forgetting things like this is a large part of why https://github.com/HypothesisWorks/hypothesis-python/issues/408 is a good idea.
