### ISSUE TITLE
Django models strategy can produce unexpected duplicate model instances

### ISSUE THREAD

**Issue by inglesp** [HypothesisWorks/hypothesis-python#419]
I have the following in a test:

```
user1 = data.draw(hypothesis_models(User))
user2 = data.draw(hypothesis_models(User))
```

I expect this to produce two distinct `User` objects.  However, hypothesis can and will produce duplicates.  This is because `ModelStrategy.do_draw` uses `get_or_create` which will reuse model instances where possible.

Here's a test case to illustrate the problem:

```
    @given(models(Company), models(Company))
    def test_given_model_instances_are_different(self, company1, company2):
        self.assertNotEqual(company1, company2)
```

This behaviour was introduced in 7ad6e44461909c36c0fe9bc7573bc4f155c7cf9d, and I think that this commit should be reverted.  Is it the case that `get_or_create` was only added as a performance optimisation?

**Comment by DRMacIver** [comment]
No, this is kinda a deliberate feature. In general it's useful for strategies to be able to produce duplicates. Is there a reason you would expect otherwise?

**Comment by inglesp** [comment]
I think I'd expected otherwise because I'd assumed that eg `user1 = data.draw(hypothesis_models(User))` was morally equivalent to eg `user1 = UserFactory()`.

I can see that it makes sense for Hypothesis to allow drawing duplicates.  Sorry for the distraction!
