### ISSUE TITLE
Same type range specification for datetimes and related

### ISSUE THREAD

**Issue by piccolbo** [HypothesisWorks/hypothesis-python#421]
I was a little surprised to find out that the generation of datetimes can only be constrained by year, an integer. First I think that any range generator of totally ordered type T should be constrained by two values of the same type. Would you constrain a unform distribution by an  integer range? I don't know of one stat library that does that. Second, my use case is generating past or future dates only with respect to the current time. The implementation has some subtlety to it if we want to ensure uniform distribution, but it's not clear to me this is guaranteed now. This is an interface changing API. Backward compatibility can be ensured by keeping the current year args, to be deprecated at some later time.

**Comment by Zac-HD** [comment]
First: sounds reasonable to me.  TODO:

- Change `datetimes` and `dates` to be constrained by `datetime` and `date`  objects respectively.  If `datetimes` is constrained by a `date` or vice-versa, that should be converted automatically.
- Handle deprecation of integer `{max,min}_year` arguments.  Warning should upgrade to an error if a datetime bound is supplied - no mixing old and new styles.
- Add optional max_time and min_time to `times` for consistency.

Second: Hypothesis doesn't make any guarantees about the distribution, but it's probably not uniform.  I would also be extremely cautious about introducing checks for the current time into your tests, as it's an infamous cause of flakiness.

To generate past and future dates with respect to the current time, I'd suggest using an integers strategy to generate timedeltas (until #333 is resolved) and adding them to the current date.

**Comment by Zac-HD** [comment]
Closed by #621.
