### ISSUE TITLE
Composite decorator doesn't preserve docstring

### ISSUE THREAD

**Issue by piccolbo** [HypothesisWorks/hypothesis-python#422]
Seems like a nice to have at least when creating a lib of strategies for others to use

**Comment by piccolbo** [comment]
Sampled from has the same problem. Maybe all decorators? Fix could be as simple as decorating all decorators with decorator.decorator and no, it's not a tongue twister.

**Comment by alexwlchan** [comment]
Yep. Here’s a simple repro, based on the [composite example in the docs](http://hypothesis.readthedocs.io/en/latest/data.html?highlight=composite):

```python
from hypothesis.strategies import composite, integers


@composite
def list_and_index(draw, elements=integers()):
    """Returns a list and an index for that list."""
    xs = draw(lists(elements, min_size=1))
    i = draw(integers(min_value=0, max_value=len(xs) - 1))
    return (xs, i)


print(list_and_index.__doc__)
```

Patch coming shortly.
