### ISSUE TITLE
Use of sampled_from({1, 2, 3}) will not save properly

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#423]
Currently if you do sampled\_from({1, 2, 3}) it will "work", but the example will not save in a reasonable manner because the iteration order is not stable - it will be saved as the position in the iteration, which can change between process runs. On Python 3 with hash randomisation it will be particularly confusing. On Python 2 it probably won't matter much unless the values being used have an identity based hash.

The same thing would happen with a dictionary or anything else where the hash iteration order varies.

The best thing to do here is probably to raise a TypeError if the argument being passed isn't an instance of collections.Sequence: Anything else might have an unreliable iteration order.

(This does unfortunately break some things that currently work fine, but changing the arguments to a list/tuple is no great hardship)

This is a breaking API change, so would have to start out by deprecating it and then changing it to an error in a later version.

**Comment by Zac-HD** [comment]
Hmm, I do like being able to pass a dict or do some quick set operations inline.  What about sorting non-sequence collections?  

`elements if isinstance(elements, collections.Sequence) else sorted(elements)` would work nicely in most scenarios - the deprecation would then only affect unordered collections of unorderable objects.  The code to detect and give sensible error messages on this case might not fit on a ternary line though!
