### ISSUE TITLE
Seeking advice about setting limits on strategy that builds strings from a regular grammar

### ISSUE THREAD

**Issue by mulkieran** [HypothesisWorks/hypothesis-python#426]
My basic problem is covered in this issue: https://github.com/stratis-storage/hs-dbus-signature/issues/6.

I'm mostly seeking advice on a way to set limits while using the recursive() strategy, or possibly an alternative approach that does not use the recursive() strategy, but still gets the benefits.

**Comment by Zac-HD** [comment]
Per my comment in the other thread, I'd use an outer function decorated with `st.composite`, and an inner function that passed the `draw` object and current limits around as it recurs.
