### ISSUE TITLE
Can we improve the Hypothesis build times?

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis-python#444]
The [last completed Travis CI run](https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/200165015) took nearly four hours to run, 75 minutes elapsed.

Admittedly the testing for Hypothesis is extensive, but I’d like to spend some time thinking about whether we can improve those times.

**Comment by alexwlchan** [comment]
(Low-hanging fruit: why do we still have _three_ jobs for `check-fakefactory` versions when we don’t even use fake-factory any more?!)

**Comment by DRMacIver** [comment]
> Why do we still have three jobs for check-fakefactory versions when we don’t even use fake-factory any more?

hypothesis.extra.fakefactory still exists (but I think we should deprecate it). OTOH I'm happy to just drop official support for old faker versions.

* What is taking 37 minutes (2231.44s) to setup before we even run any tests in this check-python34 job? Similar other jobs.

I have two theories: 

* cache misses. The different Python versions are (sadly) built from source. This is supposed to be cached but I'm suspicious that it might not always be working very well. However I can't find any evidence of this having happened in that job.
* I think Travis workers just sometimes go to sleep for a while. If so there's not much we can do about it.

It might be helpful to add more verbose timing information to the test run. I'm not sure what the best way to do that is but I'll have a think about it.

Beyond that I think there are three general approaches we can for improving build times:

* Build less stuff. e.g. we've currently got tests/cover and tests/nocover. We could more explictly make that tests/fast and tests/slow and run the slow tests on fewer versions of Python (e.g. 2.7, 3.6, pypy).
* Quash individual slow tests: pytest has the --durations=n flag that will show you the n slowest tests. We could just spend some time going through that and finding the most egregiously slow tests and see if we can replace them with something else.
* Make Hypothesis itself faster so the tests run faster.

Items on the list get objectively better but more work as you go down. In particular I don't know how much there is in the way of low hanging fruit for Hypothesis performance.

**Comment by DRMacIver** [comment]
An example where improving Hypothesis speed does seem to have actually helped (it's hard to tell because of Travis variability) is that it looks like https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/200038539 is a couple minutes faster on each job than the comparable https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/200313054.

So when I finally get the shrink-optimizations PR ready we'll see a small incremental gain.

My suspicion is that this is the sort of gain we'd likely see from optimisations to Hypothesis - 10% here or there. It adds up, but relative to the amount of work it takes it's not necessarily a good way of achieving this goal (though of course has other benefits)

**Comment by DRMacIver** [comment]
> What is taking 37 minutes (2231.44s) to setup before we even run any tests in this check-python34 job? Similar other jobs

Actually I think this is a misreading. That's the amount of time that running the whole job takes, minus a few incidental setup and teardown tasks. That's the time for calling "make $TASK", which is the bit that triggers the job.

**Comment by alexwlchan** [comment]
hypothesis.extra.fakefactory does exist, but it uses Faker instead of fake-factory as a dependency. Testing against three different versions of fake-factory tells us absolutely nothing interesting.

**Comment by alexwlchan** [comment]
A [more recent build](https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/202175179) – we’re under two hours! :D

**Comment by DRMacIver** [comment]
It's kinda distressing that that's cause for excitement, but yay!

**Comment by DRMacIver** [comment]
Controversial suggestion: Why don't we just turn the OSX builders off?

I don't think they've caught an interesting bug in a very long time - the only one they ever really caught was really just a difference in defaults of what was a narrow vs a wide build on OSX vs Linux. - and they make the build process drag a *lot*. How about we just don't do that?

**Comment by alexwlchan** [comment]
> Controversial suggestion: Why don't we just turn the OSX builders off?

Don’t you have plans to start putting bits of $NOTPYTHON code in the Conjecture core? While Hypothesis is pure Python I’d be happy to cut everything except Travis on Linux, but if we start invoking C or similar in the install process I’d want the cross-OS testing.

**Comment by DRMacIver** [comment]
hmm. Yeah, that's a good point.

**Comment by DRMacIver** [comment]
For comparison of how much of a problem this is, [the pytest-xdist build](https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/202636145) finished all its Linux jobs in 20 minutes wall clock time and then waited 40 minutes before the OSX builds started. :-(

**Comment by DRMacIver** [comment]
Here's an option worth considering: Circle CI do OSX builders now and do offer them free for open source projects. We could look into using Circle to do OSX instead of Travis.

**Comment by alexwlchan** [comment]
> Circle CI do OSX builders now and do offer them free for open source projects. We could look into using Circle to do OSX instead of Travis.

Then the OS X builds could kick off concurrently. Yeah, might be worth a shot.

(How many projects use Travis, Appveyor and Circle at the same time?)

**Comment by DRMacIver** [comment]
> How many projects use Travis, Appveyor and Circle at the same time?

I wouldn't be surprised if this were a reasonably common use case. Certainly Appveyor + Travis is pretty normal.

**Comment by maxnordlund** [comment]
About the building of python, I personally use https://github.com/pyenv/pyenv which downloads prebuilt binaries. Could be good to try, or at least use to get the pythons.

As for Circle, we used it at my last job replacing Travis, and I have mostly good experiences using it. Though we only use the Linux build, so the OSX might be funky.

Having all three also has the additional benefit of being able to quickly identify the broken platform.

**Comment by DRMacIver** [comment]
Yeah, we already use pyenv to download, but AFAICT it doesn't download prebuilt binaries for Linux? Maybe we're doing something wrong there?

We've been running OSX on Circle for a few weeks now and it's been going pretty well so far.

**Comment by maxnordlund** [comment]
> Yeah, we already use pyenv to download, but AFAICT it doesn't download prebuilt binaries for Linux? Maybe we're doing something wrong there?

Darn it. Hm, the only other python version manager I know of is https://conda.io/miniconda.html but since I haven't tried it I don't know about the binary support

**Comment by DRMacIver** [comment]
Conda are generally all about the binaries, but I think they don't play well with pip and virtualenv.

In general I'm not sure binaries are a major problem for us - the caching works pretty well at solving this problem.

**Comment by DRMacIver** [comment]
(But the suggestions are appreciated, thank you)

**Comment by maxnordlund** [comment]
Thanks it means a lot. Well then I guess the next fruit is hanging a (fair) bit higher.

**Comment by Zac-HD** [comment]
> Conda are generally all about the binaries, but I think they don't play well with pip and virtualenv.

- conda environments replace virtualenvs (and are better isolated and easier to manage)
- you can use pip perfectly well; packages installed with conda just work
- using pip makes complex up/down/side grades with conda harder, so it's not usually recommended.  Fine in this case though - just use conda to install Python (and other things if relevant), then pip install everything else.

Check out the travis setups used by conda-forge recipes if you're interested.

**Comment by DRMacIver** [comment]
> conda environments replace virtualenvs (and are better isolated and easier to manage)

That may be so, but there's an awful lot of tooling around virtualenvs (e.g. tox) that would be annoying to replace, which is the main issue.

**Comment by Zac-HD** [comment]
I think you could still use virtualenvs *inside conda envs* or just `alias python=path/to/conda/python`, but I haven't tried this myself.

**Comment by DRMacIver** [comment]
I am actually pretty happy with Hypothesis build times these days. They could be better, but I don't think they could be a *lot* better without an absurd amount of parallelism and/or our own build infrastructure. I am inclined to close this ticket as solved. Anyone against?

**Comment by alexwlchan** [comment]
[15 minutes elapsed](https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/224275126) on the last master build is much better.

I raised this issue, so I get the final saying in closing it. 😉
