### ISSUE TITLE
Protected branches require an incredibly annoying workflow

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#452]
I propose we make master unprotected again and just adopt a formal policy of still going through pull requests for all changes and never pushing directly to master.

My reasoning is that having to be upstream of master to merge is driving me up the wall. It makes small pull requests intensely annoying and is slowing everything down.

This potentially introduces the risk of breaking master, when merges interact unexpectedly, but I think that's not a huge deal as long as we notice and fix it when it happens.

@alexwlchan, what do you think?

**Comment by alexwlchan** [comment]
> I propose we make master unprotected again and just adopt a formal policy of still going through pull requests for all changes and never pushing directly to master.

I am a tentative 👍 on this.

I don’t really mind rebasing to be upstream of master (and it’s what I’d usually do even if master wasn’t protected) – but the Hypothesis CI build times are the spanner in the works here. It’s annoying to approve a PR, say “Can you rebase”, and then wait 2+ hours for the tests to run after they’ve rebased – especially when we’re both working on a bunch of small patches at once.

**Comment by DRMacIver** [comment]
Yeah, exactly. The secondary consideration for me is that it's also annoying to have to ask external contributors to do this.

I think I'm going to go ahead and do this, but that we should keep an eye and see if we run into any problems which this would have prevented.

**Comment by DRMacIver** [comment]
Oh! Update. This is OK. There's an option on the config that lets me just remove the check that the branch is up to date. So I've just turned *that* off instead of the whole thing, which I'm much happier about.
