### ISSUE TITLE
Disable builds on changes which don't affect code

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#454]
One thing I've thought about before and is particularly relevant in the context of #444 is that it would be really nice if docs changes only run the documentation CI job rather than the whole thing.

Suggested logic is that if this is a pull request (checkable as the TRAVIS_PULL_REQUEST environment variable) and the diff from master does not include any changes to src or tests/ we don't run any of the test tasks.

I don't think there's a way to mark a build job as 'skipped' so we should probably just make them pass fast in this case.

**Comment by alexwlchan** [comment]
One approach that springs to mind is to pass the `--notest` flag to tox (which drives the vast majority of tests), which will cause it to build the test environment but not run any tests.

Doing that in a Makefile is beyond the make-fu I have available this lunchtime, but might be something there.

**Comment by Zac-HD** [comment]
[Travis can run things conditionally](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/), but it's probably not useful to us (filtering on eg branch name).  Exiting early is probably the way to go.

A finer-grained approach would be to use [`pytest-testmon`](https://github.com/tarpas/pytest-testmon/) or [`smother`](https://github.com/chrisbeaumont/smother) to select only tests that are affected by changes made in the diff from master.  This is substantially harder to set up, but potentially much faster for some pulls - for example it would automatically skip most tests when editing docstrings only, where a per-job early exit would run them all.  May or may not be worth doing, but certainly interesting!

**Comment by alexwlchan** [comment]
We could filter the “deploy” job using Travis build jobs.

Otherwise I’ve successfully implemented conditional builds in another repo; see https://github.com/wellcometrust/platform/blob/master/.travis/tooling.py (Much of which is in turn borrowed from hypothesistooling.py!)

We’d have to define our own rules, but even something fairly coarse like “skip main tests if no changes to setup.py, src or tests” might have a noticeable reduction in build contention.

**Comment by Zac-HD** [comment]
Sounds great - maybe we can retry #850 now that build stages are more mature 😄

**Comment by Zac-HD** [comment]
Closed by #1014 IMO.
