### ISSUE TITLE
`test_re_evals` fails with Python 3.3

### ISSUE THREAD

**Issue by FRidh** [HypothesisWorks/hypothesis-python#477]
The test `test_re_evals` fails with Python 3.3 but succeeds with other versions.
```
=================================== FAILURES ===================================
________________________________ test_re_evals _________________________________
tests/cover/test_pretty.py:707: in test_re_evals
    assert repr(eval(pretty.pretty(r), globals())) == repr(r)
E   assert '<_sre.SRE_Pa...7fffeea83a80>' == '<_sre.SRE_Pat...7fffeea83c60>'
E     - <_sre.SRE_Pattern object at 0x7fffeea83a80>
E     ?                                        ^^
E     + <_sre.SRE_Pattern object at 0x7fffeea83c60>
E     ? 
```

**Comment by DRMacIver** [comment]
Python 3.3 isn't a supported version for Hypothesis (supported versions are latest pypy, CPython 2.7 and CPython 3.4+) . Is there a particular reason you want it?

**Comment by FRidh** [comment]
While fixing an issue for another package on our distro I encountered this. It's an (indirect) test dependency of `ipython`. Anyway, that's clear. Thanks for the quick reply!
