### ISSUE TITLE
timeout granularity

### ISSUE THREAD

**Issue by ryanfox** [HypothesisWorks/hypothesis-python#478]
Hi there, I'm looking at the documentation for the `timeout` setting: http://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.timeout

    Once this many seconds have passed, falsify will terminate even if it has not found many examples.
    This is a soft rather than a hard limit - Hypothesis won’t e.g. interrupt execution of the called function to stop it.

seems to imply the timeout is for one entire test (i.e., a function).  Is that the case?

If so, is there a way to set a per-example timeout, or hard limit?

Thanks!

**Comment by DRMacIver** [comment]
On 14 March 2017 at 05:12, Ryan Fox <notifications@github.com> wrote:

> Hi there, I'm looking at the documentation for the timeout setting:
> http://hypothesis.readthedocs.io/en/latest/settings.html#
> hypothesis.settings.timeout
>
> Once this many seconds have passed, falsify will terminate even if it has not found many examples.
> This is a soft rather than a hard limit - Hypothesis won’t e.g. interrupt execution of the called function to stop it.
>
> seems to imply the timeout is for one entire test (i.e., a function). Is
> that the case?
>
> Yes, that's correct.


> If so, is there a way to set a per-example timeout, or hard limit?
>

No. Sadly this is very hard to make work correctly (either in Python or in
general).

**Comment by ryanfox** [comment]
Got it.  Thanks for the info.
