### ISSUE TITLE
We should have an explicit review checklist

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#505]
As the team of maintainers grows, it'd be nice to have some degree of standardisation of what we look for in our review process. The idea isn't to make it completely uniform (if it were, we'd just add more steps to Travis), but to highlight what reviews should be looking at (which is also useful for people when they're writing the code).

[Checklists are supposedly very helpful for this](http://www.drmaciver.com/2016/11/review-of-a-book-that-reviews-reviewing/), so let's have one!

This issue is partially for discussing what should go in that list.

Here are my initial suggestions of some questions to ask:

* Does this introduce a change to the public API and if so is this documented?
* Does this introduce a breaking change to a public API?
* How does this code behave in response to invalid inputs, and are the resulting error messages sufficiently clear?
* Is any new functionality adequately tested?
* If this fixes a bug, is there a more general class of versions of that bug that we should look for?

Do those seem good? Any others people would like?

**Comment by Zac-HD** [comment]
I'm certainly a fan of checklists, at least for anything that can't be automated!  I'd add a section to `CONTRIBUTING.rst` explaining the *why* of the process generally and linking to any relevant reading -
 clearly marked as optional.  Extra question: (with thanks to NASA)

- What test or process could we use to prevent this kind of bug/defect/problem arising in future?

**Comment by DRMacIver** [comment]
That was sort of what I was getting at with my last listed question, though I like your/NASA's version better, thanks.

**Comment by Zac-HD** [comment]
I think it's useful to have both, to explicitly consider *what might be broken in our current code* and then *how do we avoid breaking things* - one is about state, and the other process.

I plan to review #498 and #502 in detail by the end of the weekend, and I'll try using/evolving/taking notes on this checklist as I go.  Should be interesting!

**Comment by Zac-HD** [comment]
After reviewing #509 as a test case, the checklist so far is mostly inapplicable.  We should probably think about what needs to be checked for internals changes, but not much springs to mind.  Maybe something about checking for and updating any related issues?

**Comment by froztbyte** [comment]
Having just gone through a first attempt at reviewing #524 (which went #524 -> #523 -> #511) I rapidly approached the threshold of my knowledge about Hypothesis internals. Related to @Zac-HD's last comment, a "what this changes" _along_ with a "what I think this may change" clause/blurb written by the author would at least give a clearer starting direction.

**Comment by froztbyte** [comment]
Something else: the reviewers on hypothesis-python have a small localized set of terms (`meta`, `nit`, etc) that I've already picked up on. Worth making these explicit (either plain listing or codifying them) in a document somewhere?

**Comment by DRMacIver** [comment]
I have updated this as follows:

* I've created a guides directory in the repo, for general documentation on Hypothesis *development*, and added this as guides/review.rst
* I have updated CONTRIBUTING to point people towards that along with some necessary associated fixes to it.
* I have updated it in light of #537 to make it clear that the result of a merge is a release and that changelog and version should be kept up to date.

**Comment by DRMacIver** [comment]
> Something else: the reviewers on hypothesis-python have a small localized set of terms (meta, nit, etc) that I've already picked up on. Worth making these explicit (either plain listing or codifying them) in a document somewhere?

It probably is, but I don't know that we have any formal definitions for a lot of them. They're just local dialect, mostly due to a mix of me and @alexwlchan I think.

**Comment by alexwlchan** [comment]
> Something else: the reviewers on hypothesis-python have a small localized set of terms (meta, nit, etc) that I've already picked up on. Worth making these explicit (either plain listing or codifying them) in a document somewhere?

"nit" is definitely one of mine. It’s just a shorthand for “this is a very minor comment”, e.g. typo or linting bug. My code reviews often have a lot of comments, and it’s just a convenient way to sort comments into categories of importance.

**Comment by froztbyte** [comment]
> “nit” is one of mine, from “nitpick”. It’s just a shorthand for “this is a very minor comment”, e.g. typo or linting bug. My code reviews often have a lot of comments, and it’s just a convenient way to sort comments into categories of importance.

I think that's fine - I more meant my remark as "this is something that I notice that serves with fair utility here". A dialect (however small) may be a nice thing in the greater scope of further pull requests coming through over time - allows a PR creator to quickly and easily see what is meant by something. Sort of like TLP does for document/information distribution.

Over the next while I'll keep an eye out and see if I can pick out enough of them to put together a small PR for it.

**Comment by Zac-HD** [comment]
Closed by #527.
