### ISSUE TITLE
How do I use strategies.data with @example?

### ISSUE THREAD

**Issue by Daenyth** [HypothesisWorks/hypothesis-python#519]
Currently the best I can figure out is to do
```
@given(st.integers(), st.data())
@example(1, st.data().example())
def test_foo(value, data):
    pass
```

But the above doesn't work:

```
E   InvalidArgument: Cannot call example on a DataStrategy. You should probably be using @composite for whatever it is you're trying to do.
```

**Comment by DRMacIver** [comment]
Unfortunately, you can't currently. I have some ideas for how to fix this - roughly just creating a dummy version of the data object you can pass in that draws from an array you give it - but at present there's no API for this.

**Comment by Zac-HD** [comment]
This should probably be considered a bug in the docs.  We should note that `data` is incompatible with `@example`, and suggest that `composite` (or `streaming`?) might provide an alternative.
