### ISSUE TITLE
The data strategy isn‘t documented

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis-python#521]
Spotted while triaging #519.

It doesn’t appear anywhere in <http://hypothesis.readthedocs.io/en/latest/data.html?highlight=data>.

**Comment by alexwlchan** [comment]
Additionally, the docstring for that strategy says "See the rest of the documentation for more complete information.", but I have no idea what it's referring to.

**Comment by DRMacIver** [comment]
https://hypothesis.readthedocs.io/en/latest/data.html?highlight=data()#drawing-interactively-in-tests ?

I think this is part of the more general problem that the documentation is rather poorly organised.
