### ISSUE TITLE
test_interleaving_engines is still flaky

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#571]
As per @Zac-HD's [comment here](https://github.com/HypothesisWorks/hypothesis-python/issues/534#issuecomment-296443922). [Example build](https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/224772882)

It's interesting that that's failing on the 273 build. 2.7.3 has some additional special handling be cause struct.unpack can't handle bytearray there. Perhaps we're doing something wrong in the handling of that? Have we seen it fail on the main 2.7 build recently?

**Comment by Zac-HD** [comment]
We've had some internals changes and I haven't seen this fail in quite a while, so I'm closing the issue.  Not really ideal, but it's hard to make a test that hasn't flaked less flaky!
