### ISSUE TITLE
Regression in ability to handle flatmap based rectangular lists

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#581]
As per https://github.com/HypothesisWorks/hypothesis-python/issues/533#issuecomment-296700825 the following used to work:

```python
from hypothesis import find
from hypothesis.strategies import lists, integers

def test_rectangular_lists():
    rectangle_lists = integers(min_value=0, max_value=10).flatmap(
        lambda n: lists(lists(integers(), min_size=n, max_size=n)))
    assert find(rectangle_lists, lambda x: len(x) >= 10) == [[]] * 10
```

Now it returns `[[0]] * 10` , which is weird - intuitively there's no reason the inner values should be non-empty, it's just that the shrinker can't find the better example..

**Comment by Zac-HD** [comment]
Closed by either #996 or #1006.
