### ISSUE TITLE
Feature request - Half-open intervals

### ISSUE THREAD

**Issue by ckaran** [HypothesisWorks/hypothesis-python#62]
Thanks to David's comment on [Issue 61](https://github.com/DRMacIver/hypothesis/issues/61), I've discovered the joys of `hypothesis.specifiers`, which solved the problem in that issue.  Reading through the code I've noticed that `floats_in_range()` doesn't permit `float('inf')` as a value in a range.  I'd like to suggest permitting `float('inf')` and `float('-inf')` as values so that we can test half-open intervals.  In short, `floats_in_range(0, float('inf'))` would be similar to `strategy(floats_in_range(0, sys.float_info.max)) | strategy(just(float('inf')))`, and `floats_in_range(float('-inf'), 0)` would do something similar.

**Comment by DRMacIver** [comment]
Using infinity as an endpoint is a good idea which I really should support. I'll look into it.

For the moment it's probably worth noting that the distribution of floats in range is, uh, not very good about endpoints right now, and will probably never give you them except after simplification. 

Also if you want to know the full joy of the sort of data you can get from Hypothesis, http://hypothesis.readthedocs.org/en/latest/data.html has a pretty comprehensive guide.

**Comment by ckaran** [comment]
I just tested the following, just to see if it would work:

```python
>>> random.expovariate(1/sys.float_info.max)
7.144010472452061e+307
>>> random.expovariate(1/sys.float_info.max)
8.694608057764216e+307
>>> random.expovariate(1/sys.float_info.max)
inf
>>> random.expovariate(1/sys.float_info.max)
1.104368708644848e+308
>>> random.expovariate(1/sys.float_info.max)
```

Which suggests that if you want to, you could adapt over the argument to `random.expovariate()` to get values.  Another option would be to maintain a vector of arguments and perform a linear adaptation like so:

```python
def adaptive_random(mean, variance):
    if random.choice([True, False]):
        return random.expovariate(mean) + random.expovariate(variance)
    else:
        return random.expovariate(mean) + random.expovariate(-variance)
```

That separates the mean and variance from one another.  You can keep playing more and more tricks like that, but the further you go in that direction, the better off you are in using some machine learning framework to generate examples (I'm somewhat partial to [scikit-learn](http://scikit-learn.org), but [DEAP](https://github.com/DEAP/deap) might also be a good thing to look into).  The downside to that approach is that you'll be dependent on an external framework, which might not be as bug-free as Hypothesis. 

I actually read that page, but my eyes just skimmed over the important bits the first time through...

**Comment by DRMacIver** [comment]
The standard float strategy already does most of what you're talking about and a bit more. It's just the interval strategies that are currently a bit naive.

Believe me, I'd love to pull in numpy or more as dependencies for Hypothesis, but it's something of a non-starter. Adding complex dependencies to core Hypothesis makes using it much more of a hassle for people, so there's a zero dependency policy in the core library. Dependencies get added to hypothesis-extra packages.

**Comment by ckaran** [comment]
I'm impressed, and I'll have to read the code more carefully then!

Your policy makes sense.  If nothing else, at least you have control over your bugs!

**Comment by Zac-HD** [comment]
@DRMacIver, by my reading the current `floats(0)` strategy would give you positive values including infinity.  Are the any other concerns about distribution, or should the issue be closed?
