### ISSUE TITLE
Deployment of 3.8.4 and 3.8.5 has failed

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#634]
PyPI Error 500 for  [3.8.4](https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/232734534) and [3.8.5](https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/232749840); I've tried restarting the job a few times in case of transient failure but that didn't work.

@DRMacIver, I think this is a case for your private key or admin powers.

**Comment by DRMacIver** [comment]
I've fixed these by doing manual releases, but there's an underlying problem that I don't have time to fix right this minute. I'll open another issue about it.
