### ISSUE TITLE
Our deploy job on Travis should fill in the version number and release date

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#636]
Extracted from #555 [here](https://github.com/HypothesisWorks/hypothesis-python/issues/555#issuecomment-301684082).

Having to regularly bump the changelog date in a pull request is pretty annoying, as is resolving trivial merge conflicts in `version.py`.  We should just automate this away!

- When opening a pull request, you write a changelog entry.  Instead of heading it with `maj.min.patch - YYYY-MM-DD`, you ignore the date and declare which part of the version number will be incremented when the pull is merged (one of `RELEASE_PATCH`, `RELEASE_MINOR`, or `RELEASE_MAJOR`; the last should probably be restricted to commits by @DRMacIver)

- When a pull is merged, the deploy job calculates the correct version tuple and edits `version.py`, and replaces the token in `changelog.rst` with the version string and current date.  This is then committed, tagged, and pushed to master, and the release then proceeds as usual.

No more merge conflicts, no more maintaining four pulls with the same proposed version number, and no more build failures because the date is wrong.  Bliss!

**Comment by DRMacIver** [comment]
So there are some complications with this that are going to make it annoying to resolve.

In particular what do we do in the case where there are *two* pending releases that have been merged to master? We cannot easily just commit and push then, because now the next release (which is already queued to build) will not be ahead of this one.

**Comment by Zac-HD** [comment]
(semi-serious)  Can we just `git pull` first?

**Comment by DRMacIver** [comment]
No because then we'd be releasing the later version of the code (or tagging the version which still has the TBD markers in it).

**Comment by DRMacIver** [comment]
BTW one possible fix to this which I'm increasingly in favour of is to switch to at-most-daily releases and have the deploy be from a cron job.

**Comment by Zac-HD** [comment]
I think you'd have similar issues with reconciling the changelog appropriately, except now there's also a (slightly variable) deadline to get the merge right.  I also do like the idea that each independent change gets a release.

An alternative idea - if the version and changelog bumps are automated, we're less likely to see the 'bursty' pattern where several of us are online at once, and multiple approvals are finalised and merged together.  Could we just approve pulls, and not merge until after the previous one has release?

**Comment by DRMacIver** [comment]
> I think you'd have similar issues with reconciling the changelog appropriately, except now there's also a (slightly variable) deadline to get the merge right

I think it's fine: The big problem with doing it on each merge is that you end up with releases where one is not downstream of the other. Here the separation means there's no problem with just committing, tagging, then doing a git pull to fetch the latest master and merging in the tag.

**Comment by DRMacIver** [comment]
> Could we just approve pulls, and not merge until after the previous one has release?

I'd rather not rely on us having to manually remember to get merge times right.

**Comment by Zac-HD** [comment]
Imagine that I merge a patch with `PATCH_RELEASE` (eg 3.9.2), then another with `MINOR_RELEASE` (3.10.0).  A day later, can I `pip install hypothesis=3.9.2` - or does that make it into the changelog but not onto PyPI?

**Comment by Zac-HD** [comment]
Closed by #787 (I hope hope hope)
