### ISSUE TITLE
Reduce Pyup dependency churn

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#680]
A solid majority of our pull requests are simple dependency updates, which is placing undue strain on reviewers and our CI queues - especially when a single package updates several times in one day, as requests and isort have done recently.

Weekly batch updates seem like a good balance - ensuring we have very recent versions without the current churn - but our `check-requirements` CI job would fail when a newer release is available but unmerged.  I propose to

- [ ] reduce the Pyup frequency to weekly (see #675, replaced by this issue)
- [ ] add a filter to the `check-requirements` job, so it only fails if a pinned version that `pip-compile` would update has been superseded for at least eight days.  This check can use the release-date history from PyPI ([eg](https://pypi.python.org/pypi/hypothesis/json)), and should be pretty quick if it caches responses and minimises downloads.

**Comment by alexwlchan** [comment]
I’d swear there was already an issue about this?

**Comment by alexwlchan** [comment]
Ah, I was thinking of #675.

**Comment by alexwlchan** [comment]
> reduce the Pyup frequency to weekly

No particular objections, although I’d prefer we just had a way to auto-merge PyUp PRs.

> add a filter to the check-requirements job, so it only fails if a pinned version that pip-compile would update has been superseded for at least eight days. This check can use the release-date history from PyPI

That requires us to do a bunch more checking and parsing of the requirements files and so on, where previously we could just hand that off to pip-tools. I’d be disinclined to pull in extra complexity like that to the build system – all of the other `check-{foo}` jobs bring you right up-to-date if run locally, and I think that’s a good default to preserve.

**Comment by Zac-HD** [comment]
> I’d prefer we just had a way to auto-merge PyUp PRs.

...yes, we should just do that.  Closing in favor of #616.

**Comment by The-Compiler** [comment]
I wasn't aware you could switch pyup to weekly updates, and now did so for my project - so, thanks for mentioning it! 😆
