### ISSUE TITLE
Sampled_from() should work with collections.OrderedDict

### ISSUE THREAD

**Issue by corehack** [HypothesisWorks/hypothesis-python#688]
OrderedDict should satisfy the replayability requirement, so sampling from it should be possible.
Currently it raises exception:
`HypothesisDeprecationWarning: Cannot sample from odict_values`

**Comment by mithrandi** [comment]
You could throw in a `list` call to stop Hypothesis complaining.

However, the iteration order of an `OrderedDict` is stable (obviously), so I think this ought to be allowed, unless there's some nuance I missed here.

**Comment by alexwlchan** [comment]
Yep, this seems like a straight up bug/oversight. Patch shortly.

**Comment by alexwlchan** [comment]
Okay, patch is up for review.

**Comment by alexwlchan** [comment]
@corehack This should be fixed in Hypothesis 3.11.3. Thanks for the report!
