### ISSUE TITLE
Show succeeding example?

### ISSUE THREAD

**Issue by FunkyLoveCow** [HypothesisWorks/hypothesis-python#701]
I am testing an API and have found a bug. The bug is that some data was validated when it shouldn't have been. This is a problem on the API side. 

My question, I have a list of examples in `.hypothesis/examples/<hexstring>/`. I'd like to find exactly what was sent/generated by hypothesis but the data in each of these files is unreadable. It looks nothing like the input fields that ended up in the tested system.

How can I read these example files so that I can show the succeeding example?

**Comment by DRMacIver** [comment]
Basically, you can't I'm afraid. The format in those files is very much internal, and there isn't a straightforward way to parse it outside of the context of running the test.

If you rerun the test with `HYPOTHESIS_VERBOSITY_LEVEL=verbose` set as an environment variable it will show you what examples it tries as it runs though.

**Comment by FunkyLoveCow** [comment]
That will work for my case. Thank you.
