### ISSUE TITLE
Question: Is it possible to define uuids() so that it only generates uuid4() ?

### ISSUE THREAD

**Issue by subokita** [HypothesisWorks/hypothesis-python#721]
Is it possible to define uuids() so that it only generates uuid4() ?

Since I'm testing some other stuff, I'd like to have the generators only to create uuid4s.

**Comment by DRMacIver** [comment]
It isn't, but the UUID strategy [isn't terribly complicated](https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/strategies.py#L1177), and nor is the standard library code [for generating uuid4s](https://github.com/python/cpython/blob/master/Lib/uuid.py#L631) so it shouldn't be too hard to roll your own. Something like the following should work (I've not tested it though):

```
import hypothesis.strategies as st

@st.composite
def uuid4s(draw):
    rng = draw(st.shared(st.randoms(), key='hypothesis.strategies.uuids.generator'))
    return  UUID(int=rng.getrandbits(128), version=4)
```

A pull request adding UUID version support to hypothesis.strategies would be gratefully accepted if you wanted to make one. :-)

**Comment by Zac-HD** [comment]
A good first-time contribution: add a `version=None` keyword argument to `hypothesis.strategies.uuids`, and pass it through to the call to [`uuid.UUID`](https://docs.python.org/3/library/uuid.html#uuid.UUID).
