### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by tmbb** [HypothesisWorks/hypothesis-python#724]
Is this a typo? https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/internal/conjecture/utils.py#L190

Offending code with my comments:

```python
elif truthy == 0:
    # Every other partition is falsey, so the result is true
    ## tmbb: shouldn't it be "false" instead of true?
    result = True ## tmbb: this line is overwritten by the following
                  ## tmbb: it's probably a copy-paste mistake
    result = False ## tmbb: fortunately this line undoe the damage
```

**Comment by DRMacIver** [comment]
Yes, it's a typo. Whoops! Thanks for the catch.

**Comment by Zac-HD** [comment]
@tmbb, would you like to submit a pull request fixing this and adding yourself to the contributors list?  I'd be happy to help you through the process 😄

**Comment by tmbb** [comment]
Yes, I can do it. Do I just commit against master, or is there any other workflow besides the monster travis thing?

**Comment by Zac-HD** [comment]
Great!  The ./guides/ dir has various guides for contributors, very few of which apply to this change.

- The pull can come from any branch in your fork of Hypothesis.  I always start a new branch for each pull request, but that's just to keep things organised - you *can* make a pull from `master` if you prefer to.
- Make the change in question (deleting the extra line and editing the comment)
- Add yourself to the contributors list in `CONTRIBUTING.rst`, by name or psudeonym and optionally email address, alphabetically.
- Increment the patch version in src/hypothesis/version.py
- Write a changelog entry - it can be very short, eg "Removed a small amount of dead code in the engine (:issue:\`724\`).  Thanks to new contributor tmbb for this fix."

**Comment by tmbb** [comment]
Ok, I'll do it hen I have the time
