### ISSUE TITLE
Wheel building jobs are failing (but still uploading wheels)

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#729]
See e.g. https://ci.appveyor.com/project/DRMacIver/hypothesis-python/build/1.0.1473

The end result is that the wheels still get uploaded, but there seem to be two problems:

1. Duplicate jobs are causing the second job to fail (we should probably disable one of the 32/64 bit builds until we've got a C extension)
2. Something also causing the initial upload to error despite the upload actually succeeding

This is somewhat low priority in that the job is actually "working" (I've downloaded and verified the uploaded wheels) but it's still weird and needs investigating.

**Comment by Zac-HD** [comment]
Is this still a problem now that we're only doing 64-bit builds?

**Comment by Zac-HD** [comment]
Seems to be fixed now, possibly because we don't do separate 32bit tests: https://ci.appveyor.com/project/DRMacIver/hypothesis-python/build/1.0.2765/job/ogbcfcb62yo9cyll#L2555
