### ISSUE TITLE
charmap._union_interval_lists() has has varying return types

### ISSUE THREAD

**Issue by moreati** [HypothesisWorks/hypothesis-python#735]
If one of the arguments to `_union_interval_lists(x, y)` is false-y,  then the function returns the other unmodified. However if neither is false-y, then the value returned is always a tuple. This means the return type of this function depend in the truthiness of the inputs E.g.

```python
>>> from hypothesis.internal import charmap
>>> charmap._union_interval_lists([[0,5]], [])
[[0, 5]]
>>> charmap._union_interval_lists([[0,5]], [[6,7]])
((0, 7),)
```

It's an internal API though, so does it matter?

**Comment by Zac-HD** [comment]
Hmm.  As an internal API, we can change it whenever we like - and returning a list if one input is falsey seems like a special case we don't need.  Try changing it if you like, and if the tests pass all is well 😄

**Comment by moreati** [comment]
Then, since it won't be returning a list any more, can I also change the name? E.g. to `_union_intervals()`.

**Comment by moreati** [comment]
> can I also change the name? E.g. to _union_intervals().

I'm going to assume yes, and incorporate the change into #726.

**Comment by Zac-HD** [comment]
Yep, you can make whatever internal changes make sense - and this certainly qualifies.  😄
