### ISSUE TITLE
Hypothesis should work on read-only filesystems

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#768]
- [ ] We should have sensible and useful behavior when the examples database cannot be written (#242)
- [x] We should handle other cases where writes (and subsequent reads) may fail, such as #767 
- [ ] We need a new test run for this starting with `chmod a-w -R .`

The tricky part of this is deciding what *should* happen when the example DB cannot be written to disk.  Do we explicitly fail (with an error message diagnosing the problem and noting how to use the in-memory DB from the command line), or do we log a warning and fail over to the in-memory DB?

**Comment by marcinpohl** [comment]
Try`$TMPDIR`, then `/tmp` , then `$HOME` , then `/dev/shm` in that order first.  Then log a warning and fail over to in-memory DB.

**Comment by Zac-HD** [comment]
Personally I prefer the explicit failure - not super keen on writing to someone's `$HOME` despite config, and tmpdirs are equivalent to the in-memory DB but with more serialization and IO.

**Comment by alexwlchan** [comment]
> tmpdirs are equivalent to the in-memory DB but with more serialization and IO

Depends if we can ever read it again – a file on disk persists between multiple test runs, an in-memory database doesn’t.

**Comment by CodyKochmann** [comment]
In general use terms, I'd rather hypothesis try to go in blindly in worst case scenario over it failing entirely. Maybe add warnings if not possible at all?

**Comment by Zac-HD** [comment]
\@alexwlchan, I guess tempfiles *might* persist but I'm reluctant to add OS-specific and hard-to-test fallback logic.

\@CodyKochmann, I'll take that as a vote for 'log warning and fail over to the in-memory DB'

**Comment by hangtwenty** [comment]
I'm a stranger, new to the library, just reviewing some things. If it's worth anything, I throw in a vote for the hard-failure. If you add a failover mode, agreed it could be a burden for testing ... and also, people may begin to treat it as if it's not a minimal "consolation" feature, and get more disgruntled when it works for a while then stops working ... make new feature requests ... etc. Just 2c
