### ISSUE TITLE
Our Django builds have become flaky

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#793]
At some point recently (I've only *noticed* it in the last couple of days but maybe it's been longer) our Django builds on CI have started failing pretty often with health check failures. See e.g. [here](https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/265598767).

Things I've noticed:

* This only really starts happening once the US has woken up, so it's more likely to be a load issue than something that's changed on our end.
* This has only started happening since I've noticed Travis having put us on their Trusty servers. I don't know whether that's significant or not.

**Comment by Zac-HD** [comment]
I've only seen it for the Django 1.11 job running on Trusty, and always the test_empty_slate timing out.

**Comment by DRMacIver** [comment]
> I've only seen it for the Django 1.11 

https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/265139902 has it on 1.8 and 1.10

**Comment by killthrush** [comment]
FWIW, I noticed this too with `test_is_blank_slate` over the same timeframe: https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/265557330

**Comment by DRMacIver** [comment]
`test_is_blank_slate` is the first Django test that runs, so I think the reason it's the one consistently failing is simply that when this is happening something must be cause performance to be so bad that all of the tests would fail.

**Comment by DRMacIver** [comment]
Apparently I'm wrong about the cause being `test_is_blank_slate` running first. I just saw a case where all of the others had successfully run but it had errored, and the E was somewhere in the middle of the tests (no link because I restarted the job, stupidly before copying it)

**Comment by Zac-HD** [comment]
Closed by #854.
