### ISSUE TITLE
Inconsistent acceptance of strings as bounds in hypothesis.strategies

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#814]
So it turns out that we accept string arguments as bounds for many of our strategies.

In particular all of the following accept a string argument and convert it straight through to their relevant type:

* floats
* fractions
* decimals

The following raise an InvalidArgumentError:

* dates
* times
* datetimes
* timedeltas

The following raises an internal exception:

* integers

My inclination is that the correct behaviour here is that the middle one: These should be invalid arguments. However I also feel like it's now part of our implied public API even if we never said it was valid, so *not* accepting it would be somewhat backwards incompatible.

My proposed fix:

* Fix integers to raise an InvalidArgumentError if passed something that is not a `numbers.Real`
* Fix floats, fractions, decimals, etc. to issue a DeprecationWarning if passed something that is not a `numbers.Real`

Does anyone disagree with this approach?

**Comment by Zac-HD** [comment]
Yes, actually - without loss of precision, non-integer fractions and decimals can only be constructed from a single argument with string literals.  Making users cast to the relevant type when we'll need to do it internally anyway seems needlessly verbose and frustrating.  If there was a reliable string format for dates and times I'd push to accept strings for those as well, but the ambiguity in datetime formats is legendary.

Requiring a real number for integers and floats seems sensible to me, including the hard cutover for integers and deprecation for floats.  

Actually, it occurs to me that (potential bug alert) you can bound `floats` with two decimals that don't have any floats between them... either with very small or very large values.

**Comment by DRMacIver** [comment]
> Making users cast to the relevant type when we'll need to do it internally anyway seems needlessly verbose and frustrating. 

That's fair. I'd be happy to make an explicit exemption for that case.

Note however that just passing a string to a decimal constructor is not a reliable way to construct a decimal from a string because it depends on the current decimal context. If we want to support this use case we should explicitly make sure we're using a context that traps InvalidOperation for the conversion.

**Comment by Zac-HD** [comment]
> Note however that just passing a string to a decimal constructor is not a reliable way to construct a decimal from a string because it depends on the current decimal context. If we want to support this use case we should explicitly make sure we're using a context that traps InvalidOperation for the conversion.

Hmm, maybe.  The *precision* context is irrelevant as `Decimal('1' * getcontext().prec + 1)` works just fine - constructing doesn't limit the values to those representable in the current context.  

We already handle NaN and infinite decimals, so the case where traps are disabled is already covered.  The only new code we need would be to catch InvalidOperation and reraise as InvalidArgument with a useful message.

**Comment by DRMacIver** [comment]
> We already handle NaN and infinite decimals, so the case where traps are disabled is already covered. 

Covered but I think would give a particularly bad error message. I'd rather uniformly do the conversion under a trapping context and raise an appropriate error message there, regardless of what the surrounding context is.

**Comment by Zac-HD** [comment]
@DRMacIver - I'm thinking of taking this on.  Can you confirm that the following four changes would be sufficient?

- Fix `integers` to raise an InvalidArgumentError if passed something that is not a numbers.Real
- Improve error message when `decimals` is given an invalid string in a non-trapping context
- Fix `floats` to issue a DeprecationWarning if passed something that is not a numbers.Real
- Bonus: raise an InvalidArgumentError if `floats` is passed bounds with too-high precision, like `integers` does.
  That means using the float equivalent of floor and ceil instead of nearest, and distinguishing between 'no real numbers in this interval' (eg bounds in wrong order) and 'no [double-precision] floats in this interval'.
- Continue allowing strings as args to `fractions` and `decimals`, if they can be converted to the relevant types without error
