### ISSUE TITLE
Django test_is_blank_slate fails slow generation healthcheck

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#846]
ERROR: test_is_blank_slate (tests.django.toystore.test_basic_configuration.TestConstraintsWithoutTransactions)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      ...
    hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: 
        Only produced 10 valid examples in 1.06 seconds (0 invalid ones and 0 exceeded maximum size).

This is a rare but repeated failure on Travis ([eg](https://travis-ci.org/HypothesisWorks/hypothesis-python/jobs/273811998)), hence the flaky tests label.

*However*, the actual test doesn't seem to be generating anything more than integers, which shouldn't be slow - and @DRMacIver suggested in #843 that 

> Django is a special case. In that case I'm almost certain it's not generation that's slow but Django's set up/teardown for transactional tests.

which indicates we actually have a bug in the measurement of this generation time instead, which is probably affecting many to most users of `hypothesis.extra.django`.  Instead of suggesting that the slow generation healthcheck be disabled in these cases, we should just get better at measuring generation time.

**Comment by DRMacIver** [comment]
It's being reported as part of the generation because the generation alone still has to run inside the executor. You're right that it should probably be reported differently though, and maybe this shouldn't be an error at all.

**Comment by Zac-HD** [comment]
Would it be possible to pause the timer while calling out to external code?

**Comment by DRMacIver** [comment]
Not really, without some significant reworking to a semi-public API. It would be easier to invert it and just add up the times spent between setup and teardown.

It might also be easier yet to disable the health check for these tests and make that an official recommendation for django users.
