### ISSUE TITLE
Test failure in test_minimize_list_of_sets

### ISSUE THREAD

**Issue by felixonmars** [HypothesisWorks/hypothesis-python#870]
```
tests/cover/test_simple_collections.py:125: in test_minimize_list_of_sets
    assert find(
E   assert [set([False])..., set([True])] == [set([False]),... set([False])]
E     At index 2 diff: set([True]) != set([False])
E     Full diff:
E     - [set([False]), set([False]), set([True])]
E     ?                                   ^^^
E     + [set([False]), set([False]), set([False])]
E     ?                                   ^^^^
```

Sadly I didn't keep the workdir. Hope this still helps.

**Comment by alexwlchan** [comment]
What was the environment? Versions of Hypothesis, pytest, Python, system, etc.

Test is passing fine for me locally, and in CI – but I guess it could be an environment specific thing?

**Comment by felixonmars** [comment]
Hypothesis 3.28.1, pytest 3.2.2, Python 2.7.13, Arch Linux x86_64.

A simple retry gets it to work, and I have add more tries without reproducing the problem. Maybe it's an edge-case?

**Comment by DRMacIver** [comment]
My suspicion is that the test is very slightly flaky. I have seen it become flaky occasionally in response to changes in the shrinker, so I guess it's probably right on the cusp of flakiness during normal runs.

**Comment by Zac-HD** [comment]
I accidentally made this reproducible by breaking the iteration in `hypothesis.internal.conjecture.engine.ConjectureRunner.minimize_individual_blocks` to use `for` instead of `while` and indices.  I therefore think that #1006 has made the test reliable - or at least it's non-reproducible for me despite the same change.

**Comment by felixonmars** [comment]
I still see the same test error in latest 3.43.0 release, which should have the previous fix already?

```
=================================== FAILURES ===================================
__________________________ test_minimize_list_of_sets __________________________
[gw8] linux -- Python 3.6.3 /usr/bin/python
tests/cover/test_simple_collections.py:125: in test_minimize_list_of_sets
    assert find(
E   assert [{False}, {False}, {True}] == [{False}, {False}, {False}]
E     At index 2 diff: {True} != {False}
E     Full diff:
E     - [{False}, {False}, {True}]
E     ?                     ^^^
E     + [{False}, {False}, {False}]
E     ?                     ^^^^
```

Environment:
```
platform linux -- Python 3.6.3, pytest-3.3.1, py-1.5.0, pluggy-0.6.0 -- /usr/bin/python
cachedir: .cache
benchmark: 3.1.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /build/python-hypothesis/src/hypothesis-python-3.43.0, inifile: tox.ini
plugins: hypothesis-3.43.0, xdist-1.20.1, forked-0.2, benchmark-3.1.1, flaky-3.4.0
```
