### ISSUE TITLE
Suspicious pytest failures under Windows

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#873]
The build for #860 was failing unreliably on appveyor. See e.g. [here](https://ci.appveyor.com/project/DRMacIver/hypothesis-python/build/1.0.2122/job/kc80f5998iauiqle).

This only fails sometimes and only when running the whole pytest suite.

Switching the data type in those tests from `text()` to `integers()` "solves" the problem, which makes me think this is probably some interesting interaction via the file system from writing the unicode table, but I can't think what that would be - in principle these tests *should* all be isolated, and even if they're not that shouldn't present a problem..

**Comment by Zac-HD** [comment]
I've been keeping an eye on this (and developing on Windows) and haven't noticed any problems in several months.  That's not an entirely satisfactory resolution, but without observed failures there's (a) not much we can do, and (b) little cause for concern.
