### ISSUE TITLE
Coverage ignores .coveragerc

### ISSUE THREAD

**Issue by lmshk** [HypothesisWorks/hypothesis-python#883]
Upgrading `hypothesis` beyond `3.29.0` broke our test setup: apparently, `hypothesis` now interferes with `coverage` and makes it ignore `.coveragerc`, causing lots of entries in the coverage report and violating `--fail-under=100`. (The entries now include missed paths in installed packages and in Python itself.)

(Also, the upgrade tripled test running time and caused deprecation warnings of the type "test took too long"; possibly related: #879.)

Versions:
- Python: `3.6.2`
- `hypothesis`: `3.30.0`
- `coverage`: `4.4.1`
- (`virtualenv`: `15.1.0`)

Setting `use_coverage` to `False` fixed these issues.

**Comment by DRMacIver** [comment]
Whoops, sorry! Ignoring coveragerc for our own internal usage is intended behaviour, but it certainly shouldn't be propagating excluded paths back to the enclosing coverage. That's pretty bad. I'll try to get a fix out in the next couple of days.
