### ISSUE TITLE
Exception strategy

### ISSUE THREAD

**Issue by MrGreenTea** [HypothesisWorks/hypothesis-python#885]
I have a few use cases for a strategy that generates builtin exception types.
I created such a strategy and wanted to ask, if this would be something others have a use for too.
If that is the case, I would create a Pull request.

**Comment by Zac-HD** [comment]
First, thanks for getting in touch and offering to help!  If you ever get stuck while contributing or just want a hand with Hypothesis, let me know 😄 

It sounds like your strategy would essentially be `st.sampled_from([Exception, KeyError, ValueError, ...])` - in this case we'd leave it to downstream users to implement.  If there's substantially more to it, we can talk about creating a pull request.  #750 has some relevant discussion, I think.
