### ISSUE TITLE
Failing build on master due to pulled Numpy release

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#902]
https://travis-ci.org/HypothesisWorks/hypothesis-python/builds/281109967

https://www.reddit.com/r/Python/comments/731x9g/numpy_1132_released_with_security_fix/

https://pypi.python.org/pypi/numpy/1.13.2

- [x] Wait for the Numpy team to release a fixed version
- [x] Merge the Pyup pull when it comes (or push a manual fix)
- [x] Build should pass and automatically deploy from master

Hopefully this won't push our removal of 3.3 (#862) back to after the EOL date!

**Comment by DRMacIver** [comment]
We could also just manually edit the requirements.txt and push that. Does that not work for some reason?

**Comment by Zac-HD** [comment]
*You* can! Just check the version you push carefully, and make sure you get all four requirements files.

**Comment by DRMacIver** [comment]
> You can! 

Done

>  (either 1.13.0 or 1.13.0 is the good one),

Do you mean 1.13.0 or 1.13.1? 

(hopefully because I misread it as that and changed it to 1.13.1. If not I'll push another commit to fix it at 1.13.0)

> make sure you get all four requirements files.

It only appears in two (I did a grep to be sure).

**Comment by Zac-HD** [comment]
.1 is fine, that was a mobile typo :smile:
