### ISSUE TITLE
Deadline feature interacts poorly with slow data generation in interactive examples

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#911]
It turns out that currently one of the sources of slowness in Hypothesis for large examples is that our mutation loop is actually quite slow. In particular, replaying an example from a fixed buffer is *much* faster than generating it in the first place.

This has amusing consequences for deadlines. And by amusing I mean sad.

The following script reliably fails with a flaky error from the deadline (the binary search is required because the actual timings will vary from system to system so it's hard to find the deadline needed to trigger this, but I discovered this based on a more complicated real world example):

```python
from hypothesis import given, settings, unlimited, Verbosity
import hypothesis.strategies as st
from hypothesis.errors import DeadlineExceeded


if __name__ == '__main__':
    lo = 1
    hi = 1000

    while lo + 1 < hi:
        mid = (lo + hi) // 2

        @settings(
            deadline=mid, timeout=unlimited, max_examples=10,
            verbosity=Verbosity.quiet, max_shrinks=0
        )
        @given(st.data())
        def test_slow_draw(data):
            for _ in range(1000):
                data.draw(st.binary(min_size=1, max_size=1))

        try:
            test_slow_draw()
            hi = mid
        except DeadlineExceeded:
            lo = mid
```

When I run this locally I get the following failure:

```
Unreliable test timings! On an initial run, this test took 161.08ms, which exceeded the deadline of 125.00ms, but on a subsequent run it took 78.93 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.
Falsifying example: test_slow_draw(data=data(...))
You can add @seed(302934307671667531413257853548643485645) to this test to reproduce this failure.
Traceback (most recent call last):
  File "slow_draw.py", line 24, in <module>
    test_slow_draw()
  File "slow_draw.py", line 15, in test_slow_draw
    deadline=mid, timeout=unlimited, max_examples=10,
  File "/home/david/scratch/v/lib/python3.5/site-packages/hypothesis/core.py", line 1008, in wrapped_test
    state.run()
  File "/home/david/scratch/v/lib/python3.5/site-packages/hypothesis/core.py", line 900, in run
    print_example=True, is_final=True
  File "/home/david/scratch/v/lib/python3.5/site-packages/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/home/david/scratch/v/lib/python3.5/site-packages/hypothesis/core.py", line 140, in run
    return test(*args, **kwargs)
  File "/home/david/scratch/v/lib/python3.5/site-packages/hypothesis/core.py", line 87, in test_or_flaky
    ) % (test.__name__, text_repr,))
hypothesis.errors.Flaky: Hypothesis test_slow_draw(data=data(...)) produces unreliable results: Falsified on the first call but did not on a subsequent one
```

That's quite a big timing difference! Nearly a factor of two.

I think this admits two solutions.

* As part of the Smarkets work I will be adding a feature for measuring the total amount of time spent in the test *excluding* data generation. I think the deadline should be based on that, 
* I've been thinking that we should change the interface to `ConjectureData` so that it is always initialized with a buffer anyway and remove the closure based API. This would require some revamping to the mutator, but it could probably use that anyway! This would solve the problem by making generation and shrinking the same speed (within the test function that is).

I think both solutions are worth doing on their own rights, and either would work for solving this as a problem.

**Comment by Zac-HD** [comment]
- Absolutely agree, deadlines and test timing should only measure user code and exclude data generation
- I don't understand Conjecture well enough to have an opinion on the second point

**Comment by DRMacIver** [comment]
> Absolutely agree, deadlines and test timing should only measure user code and exclude data generation

Nb. (which I forgot when writing this ticket)  this is currently the case unless you use data(). The time measured is only that of the test body, it's just that the test body sometimes contains data generation.
