### ISSUE TITLE
Mention dependencies on packaging page

### ISSUE THREAD

**Issue by cdeil** [HypothesisWorks/hypothesis-python#932]
I just noticed that hypothesis is broken in Macports because the `attrs` dependency is missing.

Apparently `attrs` was added as a required dependency in 3.28.0 - 2017-09-15 :
https://hypothesis.readthedocs.io/en/master/changes.html#id19

Here both attrs and coverage are listed as dependencies:
https://github.com/HypothesisWorks/hypothesis-python/blob/16a49c988a06d2c95bbee2e24e6638c92e81501d/setup.py#L59

Can you please update this page to explain the dependency on `attrs` and `coverage`?
https://hypothesis.readthedocs.io/en/master/packaging.html

I'll file an issue in the Macports tracker now asking them to add the attrs dependency.

**Comment by cdeil** [comment]
Also, the error I'm getting is actually for `attr`, without the "s" in `attrs`!???
```
ImportError while importing test module '/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/astropy_healpix-test-ubgaqiag/lib.macosx-10.13-x86_64-3.6/astropy_healpix/tests/test_healpy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
astropy_healpix/tests/test_healpy.py:20: in <module>
    from hypothesis import given, settings
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/hypothesis/__init__.py:27: in <module>
    from hypothesis._settings import settings, Verbosity, Phase, HealthCheck, \
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/hypothesis/_settings.py:33: in <module>
    import attr
E   ModuleNotFoundError: No module named 'attr'
```
This is horribly confusing:
* https://pypi.python.org/pypi/attr
* https://pypi.python.org/pypi/attrs

**Comment by alexwlchan** [comment]
> Also, the error I'm getting is actually for `attr`, without the "s" in `attrs`!???

Yes, the import/install mismatch is one of my least favourite features of attrs.

**Comment by cdeil** [comment]
Ah, I remember now I had looked at attrs a year ago. Yes, attrs is stuck with the distribution / package name mismatch. But long-term there might be just a new package for this that's very similar to `attrs`, but without this name confusion problem. See https://github.com/ericvsmith/dataclasses/issues/19 and https://www.python.org/dev/peps/pep-0557/

**Comment by DRMacIver** [comment]
There might be, but the chances of switching over to it are basically zero. I'm very against the idea of moving things like attrs into the standard library.

**Comment by cdeil** [comment]
Thanks!

Just for reference, if someone finds this thread in the future: the dependencies were also updated in Macports already, `port install py36-hypothesis` is working fine again.
