### ISSUE TITLE
A strategy for floats without `NaN`s and `inf`s

### ISSUE THREAD

**Issue by jacg** [HypothesisWorks/hypothesis-python#941]
I frequently find myself writing

    sensible_floats = floats(allow_nan=False, allow_inifinity=False, ...)

in my test suites. (And then weep about the length of the name `sensible_floats`.)

How would you feel about adding something approximately equivalent to

    sensible_floats = partial(floats, allow_nan=False, allow_inifinty=False)

(only with a better name) to the standard set of strategies?

My reservation about this is that providing it out of the box might encourage people to reach for it by default, in preference to `floats` without thinking about it, and thus miss a whole class of bugs.

**Comment by Zac-HD** [comment]
It *is* a common pattern - I use it (called `finite_floats`) all the time.  But I have the same concern as you; these are after all float values that the code will eventually see, and IMO users should have to explicitly think about it.

From an implementation perspective, I'm also very reluctant to add this kind of duplication to our codebase, especially when it's an obvious one-liner to add for yourself.  There's some more discussion of this in #750 and #742.
