### ISSUE TITLE
Use of the name Hypothesis

### ISSUE THREAD

**Issue by tmbb** [HypothesisWorks/hypothesis-python#951]
I'm in the process of porting hypothesis to Elixir. May I call my library Hypothesis, or is there any problem with using the name?

**Comment by DRMacIver** [comment]
I'd rather you didn't. There are eventually (quite soon, in fact!) going to be official Hypothesis ports to other languages, and it would be nice to keep the name Hypothesis distinguishing "official" ones from Hypothesis-inspired tools.

Also, aesthetically, I'd rather avoid the situation we have with QuickCheck where we have an endless proliferation of similarly things called \*check. Creative names are good.  :-)

**Comment by CodyKochmann** [comment]
I'd definitely recommend just having fun with the naming :) my testing library has things like `easy_street` for simple stuff and `violent_furniture` for the crazy stuff.

**Comment by tmbb** [comment]
I like being creative with names, no problem there :) And I'm working on a language with few packages, so there are plenty of good names available.
