### ISSUE TITLE
Remove or annotate any uses of bare `except:` from the codebase

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis-python#953]
As spotted in #952.

The new version of flake8 whinges about bare `except:`, as well it should. For now I’ve added it to the ignores list (so we can get that PR closed) – but we should go through, work out where we can do `except BaseException:` instead, and where we really want a bare `except:` (if anywhere), we explicitly annotate it with `# noqa`.

**Comment by Zac-HD** [comment]
I'd just ban bare `except`s outright - if we don't know what exception class we're trying to catch, we should reconsider the code.  Otherwise sounds great to me 😄
