### ISSUE TITLE
Settings test decorator "deadline" gives InvalidArgument error.

### ISSUE THREAD

**Issue by jason-neal** [HypothesisWorks/hypothesis-python#967]
I was trying to set a [deadline](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.deadline) for one of my tests that takes over the soon to be default 200 ms to run.

I get an invalid argument  error when trying to set a deadline using the settings decorator.
I can use other settings like `max_examples` without issue.

Here is a simple example that causes the issue.
```
import time
from hypothesis import settings

@settings(deadline=300)
#@settings(max_examples=10)
def test_long_test():
    """RV should be within theoretical limits."""
    time.sleep(1)
    assert True

```
```

❯ pytest tests/test_delay.py
============================= test session starts ==============================
platform linux2 -- Python 2.7.14, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/jneal/anaconda3/envs/obstools/bin/python
cachedir: .cache
rootdir: /home/jneal/, inifile: setup.cfg
plugins: cov-2.5.1, hypothesis-3.31.2
collected 0 items / 1 errors                                                    

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_delay.py _____________________
tests/test_delay.py:4: in <module>
    @settings(deadline=300)
../../../anaconda3/envs/obstools/lib/python2.7/site-packages/hypothesis/_settings.py:164: in __init__
    'Invalid argument %s' % (name,))
E   InvalidArgument: Invalid argument deadline
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.09 seconds ============================
```

Is this because it is not set to begin with?

**Comment by DRMacIver** [comment]
I'm almost certain you're running an old version of Hypothesis. The version of Hypothesis on Anaconda is currently quite old (there is [an ongoing issue](https://github.com/conda-forge/hypothesis-feedstock/issues/8) about keeping it up to date) - there's a broken/pulled package for a more recent version, but the current working version on anaconda is 3.23.0, which predates the deadline feature.

**Comment by jason-neal** [comment]
Ah, thanks that fixed the issue. I had to uninstall hypothesis from both pip and conda then reinstall with pip to get the latest version.
