### ISSUE TITLE
Regression in lambda inspection

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#981]
When updating the statistics output in documentation for #978 I noticed various strategies' repr no longer included the complete lambda used in defining them. e.g. the following example:

```python
from hypothesis import given, event, strategies as st

@given(st.integers().filter(lambda x: x % 2 == 0))
def test_even_integers(i):
    pass
```

When printing statistics by running this under pytest with `--hypothesis-show-statistics` the lambda used to be correctly displayed and now shows up as `lambda x: <unknown>`

**Comment by alexwlchan** [comment]
Yeah, this would have regressed in Hypothesis 3.6.0 when we removed `uncompyle6`. From the changelog:

> This release reverts Hypothesis to its old pretty printing of lambda functions based on attempting to extract the source code rather than decompile the bytecode. This is unfortunately slightly inferior in some cases and may result in you occasionally seeing things like `lambda x: <unknown>` in statistics reports and strategy reprs.

The `--hypothesis-show-statistics` flag was introduced in 3.5.0, and then the Lambda printing was broken almost immediately afterward,

**Comment by DRMacIver** [comment]
Ah, good catch. I hadn't thought we'd released any interesting features between adding and removing the decompiler, but apparently I was misremembering!

I think this can probably be fixed without adding  a decompiler back in by just extending the existing hacky solution.

**Comment by DRMacIver** [comment]
> the existing hacky solution.

TFW you'd forgotten just how bad this code past-you wrote. 😓
