### ISSUE TITLE
Test against Pandas 0.21

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis-python#983]
Should be a quickish patch to the makefile, travis config, and docs on supported versions, in `numpy.rst`.  

Also, either the existence of a pandas extra should be mentioned in `extras.rst` or (IMO) we should drop the references to extras that have their own pages.

**Comment by alexwlchan** [comment]
Before we do this, and add some more CI overhead: what’s our policy on supported Pandas releases?

For Django, the (undocumented) policy seems to be “any version still supported by Django core dev” – but I’m not a pandas user, so I don’t know if there’s an equivalent concept for pandas.

**Comment by Zac-HD** [comment]
Our policy for Django is explicit [here](https://hypothesis.readthedocs.io/en/latest/django.html) - "if you’re still getting security patches [for Django], you can test with Hypothesis".

Pandas *doesn't* have a similar system of supported versions - as far as I know they only support the latest.  Our policy ([here](https://hypothesis.readthedocs.io/en/latest/numpy.html)) is "We only commit to supporting the latest version of pandas, but older minor versions are supported on a “best effort” basis."  In practice we've never dropped support for a Pandas version, but we do skip a test under 0.18.

I'd suggest keeping it for now, not changing the policy text (except to note that we're testing 0.21), and dropping older versions when supporting them becomes inconvenient - probably 1-2 years after they were released.
