### ISSUE TITLE
regex strategy ignoring re.VERBOSE

### ISSUE THREAD

**Issue by AlvarBer** [HypothesisWorks/hypothesis-python#992]
I have a regex expression that uses re.VERBOSE flag for improved readability, and when it is used as a strategy it throws a `FailedHealthCheck`, however the same regex without the flag and compressed on a single line works fine.

I suspect this is due to `from_regex` strategy ignoring the `re.VERBOSE flag` and trying to match the full regex including whitespace and newlines, a quick search in `searchstrategy/regex.py` shows that the VERBOSE flag is not checked anywhere.

**Comment by Zac-HD** [comment]
Can you post an example of code that has this problem?

I would expect this to fail if you're just passing the pattern - but if you compile it with the `re.VERBOSE` flag it *should* work.

**Comment by Zac-HD** [comment]
Thanks for the report - your diagnosis is corrent, this is definitely a bug, and we should fix it.  Notes on that:

- We should pass the flags through to `sre_parse.parse`
- `_strategy` should take a boolean `is_text`, not the pattern itself
- We should add some tests with `re.VERBOSE` and check whether there are other neglected flags
