### ISSUE TITLE
Failure of duplication detection during generation

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis-python#995]
Found when working on something unrelated:

```python
from hypothesis import given, strategies as st


def test_count_none():
    count = 0

    @given(st.binary(min_size=9000, max_size=9000) | st.none())
    def test(n):
        nonlocal count
        if n is None:
            count += 1
    test()
    assert count <= 3
```

The inner test above should fail with some sort of error or another (could be a failed health check, could be an unsatisfiable, not sure).

What *actually* happens is that it happily keeps trying None until it runs out of testing budget. Running this with debug verbosity we see a lot of:

```
Trying example: test(n=None)
1 bytes [1] -> <Status.VALID: 2>,
1 bytes [0] -> <Status.OVERRUN: 0>,
Trying example: test(n=None)
1 bytes [1] -> <Status.VALID: 2>,
1 bytes [0] -> <Status.OVERRUN: 0>,
```

I'm not really sure what's going on here. My suspicion is something dodgy is happening in `__rewrite_for_novelty` but I've not yet dug into it. Possibly it's failing to take into account masking?

This might be a "fun" bug for anyone who wants to get more familiar with that code to work on.

**Comment by Zac-HD** [comment]
Closed by #996; this test fails the large-minimal-example healthcheck.  #1052 removes the other suspicious code, so I'm not inclined to keep digging.
